# 配置文件 - 请根据实际情况修改以下内容
# 打包后，用户可以将此文件放在 EXE 同目录下覆盖默认配置

auth:
  username: 'XXXXX'
  password: 'XXXX'

paths:
  output_dir: './data_output'
  cookie_dir: './cookies'
  captcha_dir: './captcha_images'
  log_dir: './logs'

server:
  base_url: 'https://nqi.gmcc.net:20443'
