# -*- coding: utf-8 -*-
"""地市级 NQI 报表配置。

字段项使用 NQI 协议中的 ``feild`` 等键名；``table_name`` 始终是
NQI 源表名，参考项目中的 MySQL 元数据仅作为配置审计信息保留。
"""

CITY_TABLE_CONFIGS = {'重要场景地市-天': {'name': '重要场景地市-天',
              'table_key': '重要场景-地市天',
              'db_table': 'appdbv3.a_overview_ispm_lte_city_d',
              'fieldtype': '重要场景-地市天',
              'api_type': 'table',
              'mysql_table': 'nqi_important_scene_city_day',
              'primary_key': ['city', 'starttime'],
              'tableParams': {'supporteddimension': None, 'supportedtimedimension': ''},
              'indexcount': 0,
              'dimension': {'geographicdimension': '地市',
                            'timedimension': '天',
                            'enodebField': 'enodeb_id',
                            'cgiField': 'cgi',
                            'timeField': 'starttime',
                            'cellField': 'cell',
                            'cityField': 'city'},
              'fields': [{'feild': 'starttime',
                          'feildName': '记录开始时间',
                          'table': 'appdbv3.a_overview_ispm_lte_city_d',
                          'feildtype': '重要场景-地市天',
                          'datatype': '2'},
                         {'feild': 'endtime',
                          'feildName': '记录结束时间',
                          'table': 'appdbv3.a_overview_ispm_lte_city_d',
                          'feildtype': '重要场景-地市天',
                          'datatype': '2'},
                         {'feild': 'city',
                          'feildName': '所属地市',
                          'table': 'appdbv3.a_overview_ispm_lte_city_d',
                          'feildtype': '重要场景-地市天',
                          'datatype': '2'},
                         {'feild': 'upoctudl',
                          'feildName': '4G总流量（GB）',
                          'table': 'appdbv3.a_overview_ispm_lte_city_d',
                          'feildtype': '重要场景-地市天',
                          'datatype': 'decimal',
                          'columntype': 1},
                         {'feild': 'effectiveconnmax_max',
                          'feildName': '有效RRC连接最大数_峰值',
                          'table': 'appdbv3.a_overview_ispm_lte_city_d',
                          'feildtype': '重要场景-地市天',
                          'datatype': 'integer',
                          'columntype': 1},
                         {'feild': 'connmax_max',
                          'feildName': 'RRC连接最大数_峰值',
                          'table': 'appdbv3.a_overview_ispm_lte_city_d',
                          'feildtype': '重要场景-地市天',
                          'datatype': 'integer',
                          'columntype': 1},
                         {'feild': 'effectiveconnmean_max',
                          'feildName': '有效RRC连接平均数_峰值',
                          'table': 'appdbv3.a_overview_ispm_lte_city_d',
                          'feildtype': '重要场景-地市天',
                          'datatype': 'decimal',
                          'columntype': 1},
                         {'feild': 'bh_ul_prbuse_rate',
                          'feildName': '自忙时上行PRB平均利用率(%)',
                          'table': 'appdbv3.a_overview_ispm_lte_city_d',
                          'feildtype': '重要场景-地市天',
                          'datatype': 'decimal',
                          'columntype': 1},
                         {'feild': 'bh_dl_prbuse_rate',
                          'feildName': '自忙时下行PRB平均利用率(%)',
                          'table': 'appdbv3.a_overview_ispm_lte_city_d',
                          'feildtype': '重要场景-地市天',
                          'datatype': 'decimal',
                          'columntype': 1},
                         {'feild': 'bh_pdcchcceutilratio',
                          'feildName': '自忙时PDCCH信道CCE占用率(%)',
                          'table': 'appdbv3.a_overview_ispm_lte_city_d',
                          'feildtype': '重要场景-地市天',
                          'datatype': 'decimal',
                          'columntype': 1},
                         {'feild': 'radio_succ_rate',
                          'feildName': '无线接通率(%)',
                          'table': 'appdbv3.a_overview_ispm_lte_city_d',
                          'feildtype': '重要场景-地市天',
                          'datatype': 'decimal',
                          'columntype': 1},
                         {'feild': 'radio_drop_rate',
                          'feildName': '无线掉线率(%)',
                          'table': 'appdbv3.a_overview_ispm_lte_city_d',
                          'feildtype': '重要场景-地市天',
                          'datatype': 'decimal',
                          'columntype': 1},
                         {'feild': 'call_connect_rate',
                          'feildName': '呼叫接通率(MTC+MOC)(%)',
                          'table': 'appdbv3.a_overview_ispm_lte_city_d',
                          'feildtype': '重要场景-地市天',
                          'datatype': 'decimal',
                          'columntype': 1},
                         {'feild': 'volte_drop_rate',
                          'feildName': 'VOLTE掉话率(%)',
                          'table': 'appdbv3.a_overview_ispm_lte_city_d',
                          'feildtype': '重要场景-地市天',
                          'datatype': 'decimal',
                          'columntype': 1},
                         {'feild': 'esrvcc_ho_succ_rate',
                          'feildName': 'ESRVCC切换成功率(%)',
                          'table': 'appdbv3.a_overview_ispm_lte_city_d',
                          'feildtype': '重要场景-地市天',
                          'datatype': 'decimal',
                          'columntype': 1},
                         {'feild': 'volte_voice_traffic',
                          'feildName': 'VOLTE语音话务量(Erl)',
                          'table': 'appdbv3.a_overview_ispm_lte_city_d',
                          'feildtype': '重要场景-地市天',
                          'datatype': 'decimal',
                          'columntype': 1},
                         {'feild': 'highflow_cell_count',
                          'feildName': '高流量小区数（阈值高负载）',
                          'table': 'appdbv3.a_overview_ispm_lte_city_d',
                          'feildtype': '重要场景-地市天',
                          'datatype': 'bigint',
                          'columntype': 1},
                         {'feild': 'highflow_cell_rate',
                          'feildName': '高流量小区占比（阈值高负载）(%)',
                          'table': 'appdbv3.a_overview_ispm_lte_city_d',
                          'feildtype': '重要场景-地市天',
                          'datatype': 'decimal',
                          'columntype': 1},
                         {'feild': 'highload_cell_count',
                          'feildName': '高负载小区数',
                          'table': 'appdbv3.a_overview_ispm_lte_city_d',
                          'feildtype': '重要场景-地市天',
                          'datatype': 'bigint',
                          'columntype': 1},
                         {'feild': 'highload_cell_rate',
                          'feildName': '高负载小区占比(%)',
                          'table': 'appdbv3.a_overview_ispm_lte_city_d',
                          'feildtype': '重要场景-地市天',
                          'datatype': 'decimal',
                          'columntype': 1},
                         {'feild': 'cell_count',
                          'feildName': '总小区数',
                          'table': 'appdbv3.a_overview_ispm_lte_city_d',
                          'feildtype': '重要场景-地市天',
                          'datatype': 'bigint',
                          'columntype': 1},
                         {'feild': 'bh_pdcchcceutil',
                          'feildName': '自忙时PDCCH信道CCE占用数',
                          'table': 'appdbv3.a_overview_ispm_lte_city_d',
                          'feildtype': '重要场景-地市天',
                          'datatype': 'bigint',
                          'columntype': 1},
                         {'feild': 'bh_pdcchcceavail',
                          'feildName': '自忙时PDCCH信道CCE可用数',
                          'table': 'appdbv3.a_overview_ispm_lte_city_d',
                          'feildtype': '重要场景-地市天',
                          'datatype': 'bigint',
                          'columntype': 1},
                         {'feild': 'bh_pdschprbassn',
                          'feildName': '自忙时PDSCH PRB分配数',
                          'table': 'appdbv3.a_overview_ispm_lte_city_d',
                          'feildtype': '重要场景-地市天',
                          'datatype': 'decimal',
                          'columntype': 1},
                         {'feild': 'bh_pdschprbtot',
                          'feildName': '自忙时PDSCH PRB总数',
                          'table': 'appdbv3.a_overview_ispm_lte_city_d',
                          'feildtype': '重要场景-地市天',
                          'datatype': 'decimal',
                          'columntype': 1},
                         {'feild': 'bh_puschprbassn',
                          'feildName': '自忙时PUSCH PRB分配数',
                          'table': 'appdbv3.a_overview_ispm_lte_city_d',
                          'feildtype': '重要场景-地市天',
                          'datatype': 'decimal',
                          'columntype': 1},
                         {'feild': 'bh_puschprbtot',
                          'feildName': '自忙时PUSCH PRB总数',
                          'table': 'appdbv3.a_overview_ispm_lte_city_d',
                          'feildtype': '重要场景-地市天',
                          'datatype': 'decimal',
                          'columntype': 1},
                         {'feild': 'not_zeroflow_count',
                          'feildName': '流量非零小区数',
                          'table': 'appdbv3.a_overview_ispm_lte_city_d',
                          'feildtype': '重要场景-地市天',
                          'datatype': 'bigint',
                          'columntype': 1},
                         {'feild': 'not_zeroflow_rate',
                          'feildName': '流量非零小区占比(%)',
                          'table': 'appdbv3.a_overview_ispm_lte_city_d',
                          'feildtype': '重要场景-地市天',
                          'datatype': 'decimal',
                          'columntype': 1},
                         {'feild': 'bh_peak_use_rate',
                          'feildName': '自忙时峰值利用率(%)',
                          'table': 'appdbv3.a_overview_ispm_lte_city_d',
                          'feildtype': '重要场景-地市天',
                          'datatype': 'decimal',
                          'columntype': 1},
                         {'feild': 'not_zeroflow_count_a',
                          'feildName': 'A频段流量非零小区数',
                          'table': 'appdbv3.a_overview_ispm_lte_city_d',
                          'feildtype': '重要场景-地市天',
                          'datatype': 'bigint',
                          'columntype': 1},
                         {'feild': 'upoctudl_a',
                          'feildName': 'A频段流量(GB)',
                          'table': 'appdbv3.a_overview_ispm_lte_city_d',
                          'feildtype': '重要场景-地市天',
                          'datatype': 'decimal',
                          'columntype': 1},
                         {'feild': 'upoctudl_avg_a',
                          'feildName': 'A频段平均流量(GB)',
                          'table': 'appdbv3.a_overview_ispm_lte_city_d',
                          'feildtype': '重要场景-地市天',
                          'datatype': 'decimal',
                          'columntype': 1},
                         {'feild': 'not_zeroflow_count_d',
                          'feildName': 'D频段流量非零小区数',
                          'table': 'appdbv3.a_overview_ispm_lte_city_d',
                          'feildtype': '重要场景-地市天',
                          'datatype': 'bigint',
                          'columntype': 1},
                         {'feild': 'upoctudl_d',
                          'feildName': 'D频段流量(GB)',
                          'table': 'appdbv3.a_overview_ispm_lte_city_d',
                          'feildtype': '重要场景-地市天',
                          'datatype': 'decimal',
                          'columntype': 1},
                         {'feild': 'upoctudl_avg_d',
                          'feildName': 'D频段平均流量(GB)',
                          'table': 'appdbv3.a_overview_ispm_lte_city_d',
                          'feildtype': '重要场景-地市天',
                          'datatype': 'decimal',
                          'columntype': 1},
                         {'feild': 'not_zeroflow_count_e',
                          'feildName': 'E频段流量非零小区数',
                          'table': 'appdbv3.a_overview_ispm_lte_city_d',
                          'feildtype': '重要场景-地市天',
                          'datatype': 'bigint',
                          'columntype': 1},
                         {'feild': 'upoctudl_e',
                          'feildName': 'E频段流量(GB)',
                          'table': 'appdbv3.a_overview_ispm_lte_city_d',
                          'feildtype': '重要场景-地市天',
                          'datatype': 'decimal',
                          'columntype': 1},
                         {'feild': 'upoctudl_avg_e',
                          'feildName': 'E频段平均流量(GB)',
                          'table': 'appdbv3.a_overview_ispm_lte_city_d',
                          'feildtype': '重要场景-地市天',
                          'datatype': 'decimal',
                          'columntype': 1},
                         {'feild': 'not_zeroflow_count_f',
                          'feildName': 'F频段流量非零小区数',
                          'table': 'appdbv3.a_overview_ispm_lte_city_d',
                          'feildtype': '重要场景-地市天',
                          'datatype': 'bigint',
                          'columntype': 1},
                         {'feild': 'upoctudl_f',
                          'feildName': 'F频段流量(GB)',
                          'table': 'appdbv3.a_overview_ispm_lte_city_d',
                          'feildtype': '重要场景-地市天',
                          'datatype': 'decimal',
                          'columntype': 1},
                         {'feild': 'upoctudl_avg_f',
                          'feildName': 'F频段平均流量(GB)',
                          'table': 'appdbv3.a_overview_ispm_lte_city_d',
                          'feildtype': '重要场景-地市天',
                          'datatype': 'decimal',
                          'columntype': 1},
                         {'feild': 'not_zeroflow_count_fdd1800',
                          'feildName': 'FDD1800流量非零小区数',
                          'table': 'appdbv3.a_overview_ispm_lte_city_d',
                          'feildtype': '重要场景-地市天',
                          'datatype': 'bigint',
                          'columntype': 1},
                         {'feild': 'upoctudl_fdd1800',
                          'feildName': 'FDD1800流量(GB)',
                          'table': 'appdbv3.a_overview_ispm_lte_city_d',
                          'feildtype': '重要场景-地市天',
                          'datatype': 'decimal',
                          'columntype': 1},
                         {'feild': 'upoctudl_avg_fdd1800',
                          'feildName': 'FDD1800平均流量(GB)',
                          'table': 'appdbv3.a_overview_ispm_lte_city_d',
                          'feildtype': '重要场景-地市天',
                          'datatype': 'decimal',
                          'columntype': 1},
                         {'feild': 'not_zeroflow_count_fdd900',
                          'feildName': 'FDD900流量非零小区数',
                          'table': 'appdbv3.a_overview_ispm_lte_city_d',
                          'feildtype': '重要场景-地市天',
                          'datatype': 'bigint',
                          'columntype': 1},
                         {'feild': 'upoctudl_fdd900',
                          'feildName': 'FDD900流量(GB)',
                          'table': 'appdbv3.a_overview_ispm_lte_city_d',
                          'feildtype': '重要场景-地市天',
                          'datatype': 'decimal',
                          'columntype': 1},
                         {'feild': 'upoctudl_avg_fdd900',
                          'feildName': 'FDD900平均流量(GB)',
                          'table': 'appdbv3.a_overview_ispm_lte_city_d',
                          'feildtype': '重要场景-地市天',
                          'datatype': 'decimal',
                          'columntype': 1},
                         {'feild': 'not_zeroflow_count_4g_3dmimo',
                          'feildName': '4G 3DMIMO流量非零小区数',
                          'table': 'appdbv3.a_overview_ispm_lte_city_d',
                          'feildtype': '重要场景-地市天',
                          'datatype': 'bigint',
                          'columntype': 1},
                         {'feild': 'upoctudl_4g_3dmimo',
                          'feildName': '4G 3DMIMO流量(GB)',
                          'table': 'appdbv3.a_overview_ispm_lte_city_d',
                          'feildtype': '重要场景-地市天',
                          'datatype': 'decimal',
                          'columntype': 1},
                         {'feild': 'upoctudl_avg_4g_3dmimo',
                          'feildName': '4G 3DMIMO平均流量(GB)',
                          'table': 'appdbv3.a_overview_ispm_lte_city_d',
                          'feildtype': '重要场景-地市天',
                          'datatype': 'decimal',
                          'columntype': 1},
                         {'feild': 'normal_cell_count',
                          'feildName': '常规小区数',
                          'table': 'appdbv3.a_overview_ispm_lte_city_d',
                          'feildtype': '重要场景-地市天',
                          'datatype': 'bigint',
                          'columntype': 1},
                         {'feild': 'balance_flow_rate',
                          'feildName': '均衡流量小区占比(%)',
                          'table': 'appdbv3.a_overview_ispm_lte_city_d',
                          'feildtype': '重要场景-地市天',
                          'datatype': 'decimal',
                          'columntype': 1},
                         {'feild': 'low_flow_rate',
                          'feildName': '低流量小区占比(%)',
                          'table': 'appdbv3.a_overview_ispm_lte_city_d',
                          'feildtype': '重要场景-地市天',
                          'datatype': 'decimal',
                          'columntype': 1},
                         {'feild': 'high_flow_rate',
                          'feildName': '高流量小区占比(%)',
                          'table': 'appdbv3.a_overview_ispm_lte_city_d',
                          'feildtype': '重要场景-地市天',
                          'datatype': 'decimal',
                          'columntype': 1},
                         {'feild': 'single_carrier_flow',
                          'feildName': '单载波流量(GB)',
                          'table': 'appdbv3.a_overview_ispm_lte_city_d',
                          'feildtype': '重要场景-地市天',
                          'datatype': 'decimal',
                          'columntype': 1},
                         {'feild': 'not_zeroflow_count_5g_3dmimo',
                          'feildName': '5G 3DMIMO流量非零小区数',
                          'table': 'appdbv3.a_overview_ispm_lte_city_d',
                          'feildtype': '重要场景-地市天',
                          'datatype': 'bigint',
                          'columntype': 1},
                         {'feild': 'upoctudl_5g_3dmimo',
                          'feildName': '5G 3DMIMO流量(GB)',
                          'table': 'appdbv3.a_overview_ispm_lte_city_d',
                          'feildtype': '重要场景-地市天',
                          'datatype': 'decimal',
                          'columntype': 1},
                         {'feild': 'upoctudl_avg_5g_3dmimo',
                          'feildName': '5G 3DMIMO平均流量(GB)',
                          'table': 'appdbv3.a_overview_ispm_lte_city_d',
                          'feildtype': '重要场景-地市天',
                          'datatype': 'decimal',
                          'columntype': 1},
                         {'feild': 'bh_peak_use_rate_a',
                          'feildName': 'A频段忙时峰值利用率(%)',
                          'table': 'appdbv3.a_overview_ispm_lte_city_d',
                          'feildtype': '重要场景-地市天',
                          'datatype': 'decimal',
                          'columntype': 1},
                         {'feild': 'bh_peak_use_rate_d',
                          'feildName': 'D频段忙时峰值利用率(%)',
                          'table': 'appdbv3.a_overview_ispm_lte_city_d',
                          'feildtype': '重要场景-地市天',
                          'datatype': 'decimal',
                          'columntype': 1},
                         {'feild': 'bh_peak_use_rate_e',
                          'feildName': 'E频段忙时峰值利用率(%)',
                          'table': 'appdbv3.a_overview_ispm_lte_city_d',
                          'feildtype': '重要场景-地市天',
                          'datatype': 'decimal',
                          'columntype': 1},
                         {'feild': 'bh_peak_use_rate_f',
                          'feildName': 'F频段忙时峰值利用率(%)',
                          'table': 'appdbv3.a_overview_ispm_lte_city_d',
                          'feildtype': '重要场景-地市天',
                          'datatype': 'decimal',
                          'columntype': 1},
                         {'feild': 'bh_peak_use_rate_fdd1800',
                          'feildName': 'FDD1800忙时峰值利用率(%)',
                          'table': 'appdbv3.a_overview_ispm_lte_city_d',
                          'feildtype': '重要场景-地市天',
                          'datatype': 'decimal',
                          'columntype': 1},
                         {'feild': 'bh_peak_use_rate_fdd900',
                          'feildName': 'FDD900忙时峰值利用率(%)',
                          'table': 'appdbv3.a_overview_ispm_lte_city_d',
                          'feildtype': '重要场景-地市天',
                          'datatype': 'decimal',
                          'columntype': 1},
                         {'feild': 'bh_peak_use_rate_4g_3dmimo',
                          'feildName': '4G 3DMIMO忙时峰值利用率(%)',
                          'table': 'appdbv3.a_overview_ispm_lte_city_d',
                          'feildtype': '重要场景-地市天',
                          'datatype': 'decimal',
                          'columntype': 1},
                         {'feild': 'bh_peak_use_rate_5g_3dmimo',
                          'feildName': '5G 3DMIMO忙时峰值利用率(%)',
                          'table': 'appdbv3.a_overview_ispm_lte_city_d',
                          'feildtype': '重要场景-地市天',
                          'datatype': 'decimal',
                          'columntype': 1},
                         {'feild': 'is_highflow_perceive_count',
                          'feildName': '感知高流量小区数',
                          'table': 'appdbv3.a_overview_ispm_lte_city_d',
                          'feildtype': '重要场景-地市天',
                          'datatype': 'bigint',
                          'columntype': 1},
                         {'feild': 'is_highflow_perceive_rate',
                          'feildName': '感知高流量小区占比(%)',
                          'table': 'appdbv3.a_overview_ispm_lte_city_d',
                          'feildtype': '重要场景-地市天',
                          'datatype': 'decimal',
                          'columntype': 1},
                         {'feild': 'lte_soc_tcpsetup_c_007',
                          'feildName': 'TCP连接建立成功率(%)',
                          'table': 'appdbv3.a_overview_ispm_lte_city_d',
                          'feildtype': '重要场景-地市天',
                          'datatype': 'decimal',
                          'columntype': 1},
                         {'feild': 'lte_soc_http_cell_c_055',
                          'feildName': 'HTTP业务小区平均下载速率(Mbps)',
                          'table': 'appdbv3.a_overview_ispm_lte_city_d',
                          'feildtype': '重要场景-地市天',
                          'datatype': 'decimal',
                          'columntype': 1},
                         {'feild': 'lte_soc_tcpsetup_c_003',
                          'feildName': 'TCP连接建立时延(ms)',
                          'table': 'appdbv3.a_overview_ispm_lte_city_d',
                          'feildtype': '重要场景-地市天',
                          'datatype': 'decimal',
                          'columntype': 1},
                         {'feild': 'equivalent_20m_carrier',
                          'feildName': '等效20M载波数',
                          'table': 'appdbv3.a_overview_ispm_lte_city_d',
                          'feildtype': '重要场景-地市天',
                          'datatype': 'decimal',
                          'columntype': 1},
                         {'feild': 'equivalent_20m_flow',
                          'feildName': '等效20M流量(GB)',
                          'table': 'appdbv3.a_overview_ispm_lte_city_d',
                          'feildtype': '重要场景-地市天',
                          'datatype': 'decimal',
                          'columntype': 1},
                         {'feild': 'deep_coverage',
                          'feildName': '深度覆盖小区数',
                          'table': 'appdbv3.a_overview_ispm_lte_city_d',
                          'feildtype': '重要场景-地市天',
                          'datatype': 'bigint',
                          'columntype': 1},
                         {'feild': 'singlelayer_mesh',
                          'feildName': '单层网小区数',
                          'table': 'appdbv3.a_overview_ispm_lte_city_d',
                          'feildtype': '重要场景-地市天',
                          'datatype': 'bigint',
                          'columntype': 1},
                         {'feild': 'multilayer_coverage',
                          'feildName': '多层网覆盖小区数',
                          'table': 'appdbv3.a_overview_ispm_lte_city_d',
                          'feildtype': '重要场景-地市天',
                          'datatype': 'bigint',
                          'columntype': 1},
                         {'feild': 'multilayer_capacitylayer',
                          'feildName': '多层网容量层小区数',
                          'table': 'appdbv3.a_overview_ispm_lte_city_d',
                          'feildtype': '重要场景-地市天',
                          'datatype': 'bigint',
                          'columntype': 1},
                         {'feild': 'upoctudl_tail',
                          'feildName': '尾部流量(GB)',
                          'table': 'appdbv3.a_overview_ispm_lte_city_d',
                          'feildtype': '重要场景-地市天',
                          'datatype': 'decimal',
                          'columntype': 1},
                         {'feild': 'upoctudl_tail_max',
                          'feildName': '尾部最大流量(GB)',
                          'table': 'appdbv3.a_overview_ispm_lte_city_d',
                          'feildtype': '重要场景-地市天',
                          'datatype': 'decimal',
                          'columntype': 1},
                         {'feild': 'capacitylayer_tail_rate',
                          'feildName': '容量层尾部占比(%)',
                          'table': 'appdbv3.a_overview_ispm_lte_city_d',
                          'feildtype': '重要场景-地市天',
                          'datatype': 'decimal',
                          'columntype': 1},
                         {'feild': 'province_tail',
                          'feildName': '省公司尾部指标',
                          'table': 'appdbv3.a_overview_ispm_lte_city_d',
                          'feildtype': '重要场景-地市天',
                          'datatype': 'bigint',
                          'columntype': 1},
                         {'feild': 'provincetailofcity',
                          'feildName': '省公司地市尾部指标',
                          'table': 'appdbv3.a_overview_ispm_lte_city_d',
                          'feildtype': '重要场景-地市天',
                          'datatype': 'bigint',
                          'columntype': 1},
                         {'feild': 'provincetailofcity_rate',
                          'feildName': '省公司地市尾部占比(%)',
                          'table': 'appdbv3.a_overview_ispm_lte_city_d',
                          'feildtype': '重要场景-地市天',
                          'datatype': 'decimal',
                          'columntype': 1}],
              'default_conditions': [],
              'table_name': 'appdbv3.a_overview_ispm_lte_city_d'},
 '5G容量报表-地市级': {'name': '5G容量报表-地市级',
                'table_key': '5G容量报表 - 地市级',
                'db_table': 'appdbv3.a_adhoc_capacity_nr_city',
                'fieldtype': '5G容量报表 - 地市级',
                'api_type': 'table',
                'mysql_table': 'nqi_5g_capacity_city',
                'primary_key': ['starttime', 'city'],
                'tableParams': {'supporteddimension': None, 'supportedtimedimension': '1'},
                'indexcount': 0,
                'dimension': {'geographicdimension': '地市',
                              'timedimension': '天，周，月',
                              'enodebField': 'gnodeb_id',
                              'cgiField': 'ncgi',
                              'timeField': 'starttime',
                              'cellField': 'nrcell',
                              'cityField': 'city'},
                'fields': [{'feild': 'starttime',
                            'feildName': '记录开始时间',
                            'table': 'appdbv3.a_adhoc_capacity_nr_city',
                            'tableName': '5G容量报表 - 地市级',
                            'feildtype': '5G容量报表 - 地市级',
                            'datatype': '2'},
                           {'feild': 'endtime',
                            'feildName': '记录结束时间',
                            'table': 'appdbv3.a_adhoc_capacity_nr_city',
                            'tableName': '5G容量报表 - 地市级',
                            'feildtype': '5G容量报表 - 地市级',
                            'datatype': '2'},
                           {'feild': 'city',
                            'feildName': '地市',
                            'table': 'appdbv3.a_adhoc_capacity_nr_city',
                            'tableName': '5G容量报表 - 地市级',
                            'feildtype': '5G容量报表 - 地市级',
                            'datatype': 'character varying'},
                           {'feild': 'cell_count',
                            'feildName': '总小区数',
                            'table': 'appdbv3.a_adhoc_capacity_nr_city',
                            'tableName': '5G容量报表 - 地市级',
                            'feildtype': '5G容量报表 - 地市级',
                            'datatype': 'bigint',
                            'columntype': 1},
                           {'feild': 'bh_rlc_upoctul',
                            'feildName': '自忙时RLC层上行业务字节数（G）',
                            'table': 'appdbv3.a_adhoc_capacity_nr_city',
                            'tableName': '5G容量报表 - 地市级',
                            'feildtype': '5G容量报表 - 地市级',
                            'datatype': 'decimal',
                            'columntype': 1},
                           {'feild': 'bh_rlc_upoctdl',
                            'feildName': '自忙时RLC层下行业务字节数（G）',
                            'table': 'appdbv3.a_adhoc_capacity_nr_city',
                            'tableName': '5G容量报表 - 地市级',
                            'feildtype': '5G容量报表 - 地市级',
                            'datatype': 'decimal',
                            'columntype': 1},
                           {'feild': 'bh_mac_cpoctul',
                            'feildName': '自忙时小区MAC层传输成功的上行流量（G）',
                            'table': 'appdbv3.a_adhoc_capacity_nr_city',
                            'tableName': '5G容量报表 - 地市级',
                            'feildtype': '5G容量报表 - 地市级',
                            'datatype': 'decimal',
                            'columntype': 1},
                           {'feild': 'bh_mac_cpoctdl',
                            'feildName': '自忙时小区MAC层传输成功的下行流量（G）',
                            'table': 'appdbv3.a_adhoc_capacity_nr_city',
                            'tableName': '5G容量报表 - 地市级',
                            'feildtype': '5G容量报表 - 地市级',
                            'datatype': 'decimal',
                            'columntype': 1},
                           {'feild': 'bh_pdcp_upoctul',
                            'feildName': '自忙时PDCP上行业务字节数（G）',
                            'table': 'appdbv3.a_adhoc_capacity_nr_city',
                            'tableName': '5G容量报表 - 地市级',
                            'feildtype': '5G容量报表 - 地市级',
                            'datatype': 'decimal',
                            'columntype': 1},
                           {'feild': 'bh_pdcp_upoctdl',
                            'feildName': '自忙时PDCP下行业务字节数（G）',
                            'table': 'appdbv3.a_adhoc_capacity_nr_city',
                            'tableName': '5G容量报表 - 地市级',
                            'feildtype': '5G容量报表 - 地市级',
                            'datatype': 'decimal',
                            'columntype': 1},
                           {'feild': 'bh_pdcchcceoccupancyrate',
                            'feildName': '自忙时PDCCH信道CCE占用率（%）',
                            'table': 'appdbv3.a_adhoc_capacity_nr_city',
                            'tableName': '5G容量报表 - 地市级',
                            'feildtype': '5G容量报表 - 地市级',
                            'datatype': 'decimal',
                            'columntype': 1},
                           {'feild': 'bh_prbassnrateul',
                            'feildName': '自忙时上行PRB平均利用率（%）',
                            'table': 'appdbv3.a_adhoc_capacity_nr_city',
                            'tableName': '5G容量报表 - 地市级',
                            'feildtype': '5G容量报表 - 地市级',
                            'datatype': 'decimal',
                            'columntype': 1},
                           {'feild': 'bh_prbassnratedl',
                            'feildName': '自忙时下行PRB平均利用率（%）',
                            'table': 'appdbv3.a_adhoc_capacity_nr_city',
                            'tableName': '5G容量报表 - 地市级',
                            'feildtype': '5G容量报表 - 地市级',
                            'datatype': 'decimal',
                            'columntype': 1},
                           {'feild': 'rlc_not_zeroflow_count',
                            'feildName': '日RLC层上下行总流量非0小区数（个）',
                            'table': 'appdbv3.a_adhoc_capacity_nr_city',
                            'tableName': '5G容量报表 - 地市级',
                            'feildtype': '5G容量报表 - 地市级',
                            'datatype': 'bigint',
                            'columntype': 1},
                           {'feild': 'rlc_not_zeroflow_rate',
                            'feildName': '日RLC层上下行总流量非0小区占比（%）',
                            'table': 'appdbv3.a_adhoc_capacity_nr_city',
                            'tableName': '5G容量报表 - 地市级',
                            'feildtype': '5G容量报表 - 地市级',
                            'datatype': 'decimal',
                            'columntype': 1},
                           {'feild': 'rlc_upoctul',
                            'feildName': '日RLC层上行业务字节数（G）',
                            'table': 'appdbv3.a_adhoc_capacity_nr_city',
                            'tableName': '5G容量报表 - 地市级',
                            'feildtype': '5G容量报表 - 地市级',
                            'datatype': 'decimal',
                            'columntype': 1},
                           {'feild': 'rlc_upoctdl',
                            'feildName': '日RLC层下行业务字节数（G）',
                            'table': 'appdbv3.a_adhoc_capacity_nr_city',
                            'tableName': '5G容量报表 - 地市级',
                            'feildtype': '5G容量报表 - 地市级',
                            'datatype': 'decimal',
                            'columntype': 1},
                           {'feild': 'rlc_upoctudl',
                            'feildName': '日RLC层上下行总流量（G）',
                            'table': 'appdbv3.a_adhoc_capacity_nr_city',
                            'tableName': '5G容量报表 - 地市级',
                            'feildtype': '5G容量报表 - 地市级',
                            'datatype': 'decimal',
                            'columntype': 1},
                           {'feild': 'single_carrier_flow',
                            'feildName': '地市单载波流量（G）',
                            'table': 'appdbv3.a_adhoc_capacity_nr_city',
                            'tableName': '5G容量报表 - 地市级',
                            'feildtype': '5G容量报表 - 地市级',
                            'datatype': 'decimal',
                            'columntype': 1},
                           {'feild': 'highload_cell_count',
                            'feildName': '高负荷待扩容小区数（个）',
                            'table': 'appdbv3.a_adhoc_capacity_nr_city',
                            'tableName': '5G容量报表 - 地市级',
                            'feildtype': '5G容量报表 - 地市级',
                            'datatype': 'bigint',
                            'columntype': 1},
                           {'feild': 'highload_cell_rate',
                            'feildName': '高负荷待扩容小区占比（%）',
                            'table': 'appdbv3.a_adhoc_capacity_nr_city',
                            'tableName': '5G容量报表 - 地市级',
                            'feildtype': '5G容量报表 - 地市级',
                            'datatype': 'decimal',
                            'columntype': 1},
                           {'feild': 'bh_rrc_connmean',
                            'feildName': '日均RRC连接平均数--自忙时',
                            'table': 'appdbv3.a_adhoc_capacity_nr_city',
                            'tableName': '5G容量报表 - 地市级',
                            'feildtype': '5G容量报表 - 地市级',
                            'datatype': 'character varying',
                            'columntype': 2},
                           {'feild': 'bh_rrc_connmax',
                            'feildName': '日均RRC连接最大数--自忙时',
                            'table': 'appdbv3.a_adhoc_capacity_nr_city',
                            'tableName': '5G容量报表 - 地市级',
                            'feildtype': '5G容量报表 - 地市级',
                            'datatype': 'character varying',
                            'columntype': 2},
                           {'feild': 'bh_flow_nbrattestab',
                            'feildName': '日均Flow建立请求数--自忙时',
                            'table': 'appdbv3.a_adhoc_capacity_nr_city',
                            'tableName': '5G容量报表 - 地市级',
                            'feildtype': '5G容量报表 - 地市级',
                            'datatype': 'character varying',
                            'columntype': 2},
                           {'feild': 'bh_flow_nbrsuccestab',
                            'feildName': '日均Flow建立成功数--自忙时',
                            'table': 'appdbv3.a_adhoc_capacity_nr_city',
                            'tableName': '5G容量报表 - 地市级',
                            'feildtype': '5G容量报表 - 地市级',
                            'datatype': 'character varying',
                            'columntype': 2},
                           {'feild': 'bh_kpi_flowsuccconnrate',
                            'feildName': '日均QoS Flow建立成功率-自忙时',
                            'table': 'appdbv3.a_adhoc_capacity_nr_city',
                            'tableName': '5G容量报表 - 地市级',
                            'feildtype': '5G容量报表 - 地市级',
                            'datatype': 'character varying',
                            'columntype': 2},
                           {'feild': 'bh_dtchmimoprbassnrateul',
                            'feildName': '自忙时上行业务信道空分PRB占用率',
                            'table': 'appdbv3.a_adhoc_capacity_nr_city',
                            'tableName': '5G容量报表 - 地市级',
                            'feildtype': '5G容量报表 - 地市级',
                            'datatype': 'character varying',
                            'columntype': 1},
                           {'feild': 'bh_dtchmimoprbassnratedl',
                            'feildName': '自忙时下行业务信道空分PRB占用率',
                            'table': 'appdbv3.a_adhoc_capacity_nr_city',
                            'tableName': '5G容量报表 - 地市级',
                            'feildtype': '5G容量报表 - 地市级',
                            'datatype': 'character varying',
                            'columntype': 1},
                           {'feild': 'bh_cellprbrate_max',
                            'feildName': '自忙时峰值利用率',
                            'table': 'appdbv3.a_adhoc_capacity_nr_city',
                            'tableName': '5G容量报表 - 地市级',
                            'feildtype': '5G容量报表 - 地市级',
                            'datatype': 'character varying',
                            'columntype': 1}],
                'default_conditions': [],
                'table_name': 'appdbv3.a_adhoc_capacity_nr_city'},
 '4G小区性能KPI报表-地市': {'name': '4G小区性能KPI报表-地市',
                    'table_key': '公共_4G小区性能KPI报表_小区',
                    'db_table': 'appdbv3.a_common_pm_lte',
                    'fieldtype': '公共_4G小区性能KPI报表_小区',
                    'api_type': 'table',
                    'mysql_table': 'nqi_4g_kpi_city',
                    'primary_key': ['city', 'starttime'],
                    'tableParams': {'supporteddimension': '2', 'supportedtimedimension': '1'},
                    'indexcount': 0,
                    'dimension': {'geographicdimension': '小区，网格，地市，分公司',
                                  'timedimension': '小时,天,年.月,忙时,15分钟',
                                  'enodebField': 'enodeb_id',
                                  'cgiField': 'cgi',
                                  'timeField': 'starttime',
                                  'cellField': 'cell',
                                  'cityField': 'city'},
                    'fields': [{'feild': 'starttime',
                                'feildName': '开始时间',
                                'table': 'appdbv3.a_common_pm_lte',
                                'feildtype': '公共_4G小区性能KPI报表_小区',
                                'datatype': 'character varying',
                                'columntype': 2},
                               {'feild': 'endtime',
                                'feildName': '结束时间',
                                'table': 'appdbv3.a_common_pm_lte',
                                'feildtype': '公共_4G小区性能KPI报表_小区',
                                'datatype': 'character varying',
                                'columntype': 2},
                               {'feild': 'city',
                                'feildName': '所属地市',
                                'table': 'appdbv3.a_common_pm_lte',
                                'feildtype': '公共_4G小区性能KPI报表_小区',
                                'datatype': 'character varying',
                                'columntype': 1},
                               {'feild': 'rrc_succ_rate',
                                'feildName': 'RRC连接建立成功率(%)',
                                'table': 'appdbv3.a_common_pm_lte',
                                'feildtype': '公共_4G小区性能KPI报表_小区',
                                'datatype': 'decimal',
                                'columntype': 1},
                               {'feild': 'radio_succ_rate',
                                'feildName': '无线接通率(%)',
                                'table': 'appdbv3.a_common_pm_lte',
                                'feildtype': '公共_4G小区性能KPI报表_小区',
                                'datatype': 'decimal',
                                'columntype': 1},
                               {'feild': 'radio_drop_rate',
                                'feildName': '无线掉线率(%)',
                                'table': 'appdbv3.a_common_pm_lte',
                                'feildtype': '公共_4G小区性能KPI报表_小区',
                                'datatype': 'decimal',
                                'columntype': 1},
                               {'feild': 'enbout_succ_rate',
                                'feildName': '切换成功率(%)',
                                'table': 'appdbv3.a_common_pm_lte',
                                'feildtype': '公共_4G小区性能KPI报表_小区',
                                'datatype': 'decimal',
                                'columntype': 1},
                               {'feild': 'volte_voice_traffic',
                                'feildName': 'VOLTE语音话务量',
                                'table': 'appdbv3.a_common_pm_lte',
                                'feildtype': '公共_4G小区性能KPI报表_小区',
                                'datatype': 'decimal',
                                'columntype': 1},
                               {'feild': 'upoctul',
                                'feildName': '上行流量(KByte)',
                                'table': 'appdbv3.a_common_pm_lte',
                                'feildtype': '公共_4G小区性能KPI报表_小区',
                                'datatype': 'decimal',
                                'columntype': 1},
                               {'feild': 'upoctdl',
                                'feildName': '下行流量(KByte)',
                                'table': 'appdbv3.a_common_pm_lte',
                                'feildtype': '公共_4G小区性能KPI报表_小区',
                                'datatype': 'decimal',
                                'columntype': 1}],
                    'default_conditions': [],
                    'table_name': 'appdbv3.a_common_pm_lte'},
 '5G小区性能KPI报表-地市': {'name': '5G小区性能KPI报表-地市',
                    'table_key': '公共_5G小区性能KPI报表_小区',
                    'db_table': 'appdbv3.a_common_pm_sacu',
                    'fieldtype': '公共_5G小区性能KPI报表_小区',
                    'api_type': 'table',
                    'mysql_table': 'nqi_5g_kpi_city',
                    'primary_key': ['city', 'starttime'],
                    'tableParams': {'supporteddimension': '2', 'supportedtimedimension': '1'},
                    'indexcount': 0,
                    'dimension': {'geographicdimension': '小区，网格，地市，分公司',
                                  'timedimension': '小时,天,年,月',
                                  'enodebField': 'gnodeb_id',
                                  'cgiField': 'ncgi',
                                  'timeField': 'starttime',
                                  'cellField': 'nrcell',
                                  'cityField': 'city'},
                    'fields': [{'feild': 'starttime',
                                'feildName': '数据时间',
                                'table': 'appdbv3.a_common_pm_sacu',
                                'feildtype': '公共_5G小区性能KPI报表_小区',
                                'datatype': 'character varying',
                                'columntype': 1},
                               {'feild': 'city',
                                'feildName': '所属地市',
                                'table': 'appdbv3.a_common_pm_sacu',
                                'feildtype': '公共_5G小区性能KPI报表_小区',
                                'datatype': 'character varying',
                                'columntype': 1},
                               {'feild': 'kpi_wirelesssuccconnrate',
                                'feildName': '无线连接建立成功率(%)',
                                'table': 'appdbv3.a_common_pm_sacu',
                                'feildtype': '公共_5G小区性能KPI报表_小区',
                                'datatype': 'decimal',
                                'columntype': 1},
                               {'feild': 'kpi_hosuccoutrate',
                                'feildName': '切换出成功率(%)',
                                'table': 'appdbv3.a_common_pm_sacu',
                                'feildtype': '公共_5G小区性能KPI报表_小区',
                                'datatype': 'decimal',
                                'columntype': 1},
                               {'feild': 'kpi_wirelessdroprate_netlevel',
                                'feildName': '无线掉线率(%)',
                                'table': 'appdbv3.a_common_pm_sacu',
                                'feildtype': '公共_5G小区性能KPI报表_小区',
                                'datatype': 'decimal',
                                'columntype': 1},
                               {'feild': 'vonr_voice_traffic',
                                'feildName': 'VoNR语音话务量',
                                'table': 'appdbv3.a_common_pm_sacu',
                                'feildtype': '公共_5G小区性能KPI报表_小区',
                                'datatype': 'decimal',
                                'columntype': 1},
                               {'feild': 'kpi_pdcpupoctul',
                                'feildName': '上行流量(KByte)',
                                'table': 'appdbv3.a_common_pm_sacu',
                                'feildtype': '公共_5G小区性能KPI报表_小区',
                                'datatype': 'decimal',
                                'columntype': 1},
                               {'feild': 'kpi_pdcpupoctdl',
                                'feildName': '下行流量(KByte)',
                                'table': 'appdbv3.a_common_pm_sacu',
                                'feildtype': '公共_5G小区性能KPI报表_小区',
                                'datatype': 'decimal',
                                'columntype': 1}],
                    'default_conditions': [],
                    'table_name': 'appdbv3.a_common_pm_sacu'}}

__all__ = ["CITY_TABLE_CONFIGS"]
