# -*- coding: utf-8 -*-
"""
报表字段配置模块
包含所有报表的硬编码字段配置，与旧版保持一致
"""

# ==================== 5G干扰小区字段配置 ====================
INTERFERENCE_5G_FIELDS = [
    {'feild': 'starttime', 'feildName': '数据时间', 'datatype': 'character varying', 'columntype': '1',
     'feildtype': '5G干扰报表（忙时）', 'table': 'appdbv3.a_interfere_nr_cell_zb2_d', 'tableName': '5G干扰报表（忙时）'},
    {'feild': 'endtime', 'feildName': '结束时间', 'datatype': 'character varying', 'columntype': '1',
     'feildtype': '5G干扰报表（忙时）', 'table': 'appdbv3.a_interfere_nr_cell_zb2_d', 'tableName': '5G干扰报表（忙时）'},
    {'feild': 'cgi', 'feildName': 'CGI', 'datatype': 'character varying', 'columntype': '1',
     'feildtype': '5G干扰报表（忙时）', 'table': 'appdbv3.a_interfere_nr_cell_zb2_d', 'tableName': '5G干扰报表（忙时）'},
    {'feild': 'cell_name', 'feildName': '小区名', 'datatype': 'character varying', 'columntype': '1',
     'feildtype': '5G干扰报表（忙时）', 'table': 'appdbv3.a_interfere_nr_cell_zb2_d', 'tableName': '5G干扰报表（忙时）'},
    {'feild': 'freq', 'feildName': '频段', 'datatype': 'character varying', 'columntype': '1',
     'feildtype': '5G干扰报表（忙时）', 'table': 'appdbv3.a_interfere_nr_cell_zb2_d', 'tableName': '5G干扰报表（忙时）'},
    {'feild': 'micro_grid', 'feildName': '微网格标识', 'datatype': 'character varying', 'columntype': '1',
     'feildtype': '5G干扰报表（忙时）', 'table': 'appdbv3.a_interfere_nr_cell_zb2_d', 'tableName': '5G干扰报表（忙时）'},
    {'feild': 'averagevalue', 'feildName': '全频段均值', 'datatype': 'character varying', 'columntype': '1',
     'feildtype': '5G干扰报表（忙时）', 'table': 'appdbv3.a_interfere_nr_cell_zb2_d', 'tableName': '5G干扰报表（忙时）'},
    {'feild': 'averagevalued1', 'feildName': 'D1均值', 'datatype': 'character varying', 'columntype': '1',
     'feildtype': '5G干扰报表（忙时）', 'table': 'appdbv3.a_interfere_nr_cell_zb2_d', 'tableName': '5G干扰报表（忙时）'},
    {'feild': 'averagevalued2', 'feildName': 'D2均值', 'datatype': 'character varying', 'columntype': '1',
     'feildtype': '5G干扰报表（忙时）', 'table': 'appdbv3.a_interfere_nr_cell_zb2_d', 'tableName': '5G干扰报表（忙时）'},
    {'feild': 'is_interfere_5g', 'feildName': '是否干扰小区', 'datatype': 'character varying', 'columntype': '1',
     'feildtype': '5G干扰报表（忙时）', 'table': 'appdbv3.a_interfere_nr_cell_zb2_d', 'tableName': '5G干扰报表（忙时）'},
]

# ==================== 4G干扰小区字段配置 ====================
INTERFERENCE_4G_FIELDS = [
    {'feild': 'starttime', 'feildName': '数据时间', 'datatype': '1', 'columntype': '1',
     'feildtype': '4G干扰报表（忙时）', 'table': 'appdbv3.a_interfere_lte_cell_zb2_d', 'tableName': '4G干扰报表（忙时）'},
    {'feild': 'endtime', 'feildName': '结束时间', 'datatype': '1', 'columntype': '1',
     'feildtype': '4G干扰报表（忙时）', 'table': 'appdbv3.a_interfere_lte_cell_zb2_d', 'tableName': '4G干扰报表（忙时）'},
    {'feild': 'cgi', 'feildName': 'CGI', 'datatype': 'character varying', 'columntype': '1',
     'feildtype': '4G干扰报表（忙时）', 'table': 'appdbv3.a_interfere_lte_cell_zb2_d', 'tableName': '4G干扰报表（忙时）'},
    {'feild': 'cell_name', 'feildName': '小区名', 'datatype': 'character varying', 'columntype': '1',
     'feildtype': '4G干扰报表（忙时）', 'table': 'appdbv3.a_interfere_lte_cell_zb2_d', 'tableName': '4G干扰报表（忙时）'},
    {'feild': 'freq', 'feildName': '频段', 'datatype': 'character varying', 'columntype': '1',
     'feildtype': '4G干扰报表（忙时）', 'table': 'appdbv3.a_interfere_lte_cell_zb2_d', 'tableName': '4G干扰报表（忙时）'},
    {'feild': 'micro_grid', 'feildName': '微网格标识', 'datatype': 'character varying', 'columntype': '1',
     'feildtype': '4G干扰报表（忙时）', 'table': 'appdbv3.a_interfere_lte_cell_zb2_d', 'tableName': '4G干扰报表（忙时）'},
    {'feild': 'bandwidth', 'feildName': '系统带宽', 'datatype': 'character varying', 'columntype': '1',
     'feildtype': '4G干扰报表（忙时）', 'table': 'appdbv3.a_interfere_lte_cell_zb2_d', 'tableName': '4G干扰报表（忙时）'},
    {'feild': 'averagevalue', 'feildName': '平均干扰电平', 'datatype': 'character varying', 'columntype': '1',
     'feildtype': '4G干扰报表（忙时）', 'table': 'appdbv3.a_interfere_lte_cell_zb2_d', 'tableName': '4G干扰报表（忙时）'},
    {'feild': 'is_interfere', 'feildName': '是否干扰小区', 'datatype': 'character varying', 'columntype': '1',
     'feildtype': '4G干扰报表（忙时）', 'table': 'appdbv3.a_interfere_lte_cell_zb2_d', 'tableName': '4G干扰报表（忙时）'},
]

# ==================== 4G语音小区专用字段配置（VoLTE） ====================
VOLTE_4G_VOICE_FIELDS = [
    {'feild': 'starttime', 'feildName': '时间', 'datatype': 'timestamp', 'columntype': '1',
     'feildtype': 'VoLTE小区监控预警数据表-天', 'table': 'csem.f_nk_volte_keykpi_cell_d', 'tableName': 'VoLTE小区监控预警数据表-天'},
    {'feild': 'city', 'feildName': '地市', 'datatype': 'character varying', 'columntype': '1',
     'feildtype': 'VoLTE小区监控预警数据表-天', 'table': 'csem.f_nk_volte_keykpi_cell_d', 'tableName': 'VoLTE小区监控预警数据表-天'},
    {'feild': 'cgi', 'feildName': '小区', 'datatype': 'character varying', 'columntype': '1',
     'feildtype': 'VoLTE小区监控预警数据表-天', 'table': 'csem.f_nk_volte_keykpi_cell_d', 'tableName': 'VoLTE小区监控预警数据表-天'},
    {'feild': 'grid', 'feildName': '责任网格', 'datatype': 'character varying', 'columntype': '1',
     'feildtype': 'VoLTE小区监控预警数据表-天', 'table': 'csem.f_nk_volte_keykpi_cell_d', 'tableName': 'VoLTE小区监控预警数据表-天'},
    {'feild': 'area', 'feildName': '区县', 'datatype': 'character varying', 'columntype': '1',
     'feildtype': 'VoLTE小区监控预警数据表-天', 'table': 'csem.f_nk_volte_keykpi_cell_d', 'tableName': 'VoLTE小区监控预警数据表-天'},
    {'feild': 'nrcell_name', 'feildName': '小区名称', 'datatype': 'character varying', 'columntype': '1',
     'feildtype': 'VoLTE小区监控预警数据表-天', 'table': 'csem.f_nk_volte_keykpi_cell_d', 'tableName': 'VoLTE小区监控预警数据表-天'},
    {'feild': 'volte_ul_tunzi_len', 'feildName': 'VoLTE语音上行吞字时长(s)', 'datatype': 'character varying', 'columntype': '1',
     'feildtype': 'VoLTE小区监控预警数据表-天', 'table': 'csem.f_nk_volte_keykpi_cell_d', 'tableName': 'VoLTE小区监控预警数据表-天'},
    {'feild': 'volte_ul_dantong_len', 'feildName': 'VoLTE语音上行单通时长(s)', 'datatype': 'character varying', 'columntype': '1',
     'feildtype': 'VoLTE小区监控预警数据表-天', 'table': 'csem.f_nk_volte_keykpi_cell_d', 'tableName': 'VoLTE小区监控预警数据表-天'},
    {'feild': 'volte_ul_duanxu_len', 'feildName': 'VoLTE语音上行断续时长(s)', 'datatype': 'character varying', 'columntype': '1',
     'feildtype': 'VoLTE小区监控预警数据表-天', 'table': 'csem.f_nk_volte_keykpi_cell_d', 'tableName': 'VoLTE小区监控预警数据表-天'},
    {'feild': 'volte_ul_voice_sum_len', 'feildName': 'VoLTE语音上行总时长(s)', 'datatype': 'character varying', 'columntype': '1',
     'feildtype': 'VoLTE小区监控预警数据表-天', 'table': 'csem.f_nk_volte_keykpi_cell_d', 'tableName': 'VoLTE小区监控预警数据表-天'},
    {'feild': 'volte_ans_voice_call', 'feildName': 'VoLTE语音通话总次数', 'datatype': 'character varying', 'columntype': '1',
     'feildtype': 'VoLTE小区监控预警数据表-天', 'table': 'csem.f_nk_volte_keykpi_cell_d', 'tableName': 'VoLTE小区监控预警数据表-天'},
    {'feild': 'volte_dl_tunzi_len', 'feildName': 'VoLTE语音下行吞字时长(s)', 'datatype': 'character varying', 'columntype': '1',
     'feildtype': 'VoLTE小区监控预警数据表-天', 'table': 'csem.f_nk_volte_keykpi_cell_d', 'tableName': 'VoLTE小区监控预警数据表-天'},
    {'feild': 'volte_dl_dantong_len', 'feildName': 'VoLTE语音下行单通时长(s)', 'datatype': 'character varying', 'columntype': '1',
     'feildtype': 'VoLTE小区监控预警数据表-天', 'table': 'csem.f_nk_volte_keykpi_cell_d', 'tableName': 'VoLTE小区监控预警数据表-天'},
    {'feild': 'volte_dl_duanxu_len', 'feildName': 'VoLTE语音下行断续时长(s)', 'datatype': 'character varying', 'columntype': '1',
     'feildtype': 'VoLTE小区监控预警数据表-天', 'table': 'csem.f_nk_volte_keykpi_cell_d', 'tableName': 'VoLTE小区监控预警数据表-天'},
    {'feild': 'volte_dl_voice_sum_len', 'feildName': 'VoLTE语音下行总时长(s)', 'datatype': 'character varying', 'columntype': '1',
     'feildtype': 'VoLTE小区监控预警数据表-天', 'table': 'csem.f_nk_volte_keykpi_cell_d', 'tableName': 'VoLTE小区监控预警数据表-天'},
]

# ==================== 4G语音小区专用字段配置（EPSFB） ====================
EPSFB_4G_VOICE_FIELDS = [
    {'feild': 'starttime', 'feildName': '时间', 'datatype': 'timestamp', 'columntype': '1',
     'feildtype': 'EPSFB小区监控预警数据表-天', 'table': 'csem.f_nk_epsfb_keykpi_cell_d', 'tableName': 'EPSFB小区监控预警数据表-天'},
    {'feild': 'city', 'feildName': '地市', 'datatype': 'character varying', 'columntype': '1',
     'feildtype': 'EPSFB小区监控预警数据表-天', 'table': 'csem.f_nk_epsfb_keykpi_cell_d', 'tableName': 'EPSFB小区监控预警数据表-天'},
    {'feild': 'cgi', 'feildName': '小区', 'datatype': 'character varying', 'columntype': '1',
     'feildtype': 'EPSFB小区监控预警数据表-天', 'table': 'csem.f_nk_epsfb_keykpi_cell_d', 'tableName': 'EPSFB小区监控预警数据表-天'},
    {'feild': 'grid', 'feildName': '责任网格', 'datatype': 'character varying', 'columntype': '1',
     'feildtype': 'EPSFB小区监控预警数据表-天', 'table': 'csem.f_nk_epsfb_keykpi_cell_d', 'tableName': 'EPSFB小区监控预警数据表-天'},
    {'feild': 'area', 'feildName': '区县', 'datatype': 'character varying', 'columntype': '1',
     'feildtype': 'EPSFB小区监控预警数据表-天', 'table': 'csem.f_nk_epsfb_keykpi_cell_d', 'tableName': 'EPSFB小区监控预警数据表-天'},
    {'feild': 'nrcell_name', 'feildName': '小区名称', 'datatype': 'character varying', 'columntype': '1',
     'feildtype': 'EPSFB小区监控预警数据表-天', 'table': 'csem.f_nk_epsfb_keykpi_cell_d', 'tableName': 'EPSFB小区监控预警数据表-天'},
    {'feild': 'epsfb_ul_tunzi_len', 'feildName': 'EPSFB语音上行吞字时长(s)', 'datatype': 'character varying', 'columntype': '1',
     'feildtype': 'EPSFB小区监控预警数据表-天', 'table': 'csem.f_nk_epsfb_keykpi_cell_d', 'tableName': 'EPSFB小区监控预警数据表-天'},
    {'feild': 'epsfb_ul_dantong_len', 'feildName': 'EPSFB语音上行单通时长(s)', 'datatype': 'character varying', 'columntype': '1',
     'feildtype': 'EPSFB小区监控预警数据表-天', 'table': 'csem.f_nk_epsfb_keykpi_cell_d', 'tableName': 'EPSFB小区监控预警数据表-天'},
    {'feild': 'epsfb_ul_duanxu_len', 'feildName': 'EPSFB语音上行断续时长(s)', 'datatype': 'character varying', 'columntype': '1',
     'feildtype': 'EPSFB小区监控预警数据表-天', 'table': 'csem.f_nk_epsfb_keykpi_cell_d', 'tableName': 'EPSFB小区监控预警数据表-天'},
    {'feild': 'epsfb_ul_voice_sum_len', 'feildName': 'EPSFB语音上行总时长(s)', 'datatype': 'character varying', 'columntype': '1',
     'feildtype': 'EPSFB小区监控预警数据表-天', 'table': 'csem.f_nk_epsfb_keykpi_cell_d', 'tableName': 'EPSFB小区监控预警数据表-天'},
    {'feild': 'epsfb_ans_voice_call', 'feildName': 'EPSFB语音通话总次数', 'datatype': 'character varying', 'columntype': '1',
     'feildtype': 'EPSFB小区监控预警数据表-天', 'table': 'csem.f_nk_epsfb_keykpi_cell_d', 'tableName': 'EPSFB小区监控预警数据表-天'},
    {'feild': 'epsfb_dl_tunzi_len', 'feildName': 'EPSFB语音下行吞字时长(s)', 'datatype': 'character varying', 'columntype': '1',
     'feildtype': 'EPSFB小区监控预警数据表-天', 'table': 'csem.f_nk_epsfb_keykpi_cell_d', 'tableName': 'EPSFB小区监控预警数据表-天'},
    {'feild': 'epsfb_dl_dantong_len', 'feildName': 'EPSFB语音下行单通时长(s)', 'datatype': 'character varying', 'columntype': '1',
     'feildtype': 'EPSFB小区监控预警数据表-天', 'table': 'csem.f_nk_epsfb_keykpi_cell_d', 'tableName': 'EPSFB小区监控预警数据表-天'},
    {'feild': 'epsfb_dl_duanxu_len', 'feildName': 'EPSFB语音下行断续时长(s)', 'datatype': 'character varying', 'columntype': '1',
     'feildtype': 'EPSFB小区监控预警数据表-天', 'table': 'csem.f_nk_epsfb_keykpi_cell_d', 'tableName': 'EPSFB小区监控预警数据表-天'},
    {'feild': 'epsfb_dl_voice_sum_len', 'feildName': 'EPSFB语音下行总时长(s)', 'datatype': 'character varying', 'columntype': '1',
     'feildtype': 'EPSFB小区监控预警数据表-天', 'table': 'csem.f_nk_epsfb_keykpi_cell_d', 'tableName': 'EPSFB小区监控预警数据表-天'},
]

# ==================== 4G语音小区专用字段配置（VoLTE预警报表） ====================
# 用于4G语音小区预警报表：联合VoLTE预警和EPSFB预警表
VOLTE_4G_VOICE_WARNING_FIELDS = [
    {'feild': 'starttime', 'feildName': '时间', 'datatype': 'timestamp', 'columntype': '1',
     'feildtype': 'VoLTE小区监控预警数据表-天', 'table': 'csem.f_nk_volte_keykpi_cell_d', 'tableName': 'VoLTE小区监控预警数据表-天'},
    {'feild': 'city', 'feildName': '地市', 'datatype': 'character varying', 'columntype': '1',
     'feildtype': 'VoLTE小区监控预警数据表-天', 'table': 'csem.f_nk_volte_keykpi_cell_d', 'tableName': 'VoLTE小区监控预警数据表-天'},
    {'feild': 'cgi', 'feildName': '小区', 'datatype': 'character varying', 'columntype': '1',
     'feildtype': 'VoLTE小区监控预警数据表-天', 'table': 'csem.f_nk_volte_keykpi_cell_d', 'tableName': 'VoLTE小区监控预警数据表-天'},
    {'feild': 'grid', 'feildName': '责任网格', 'datatype': 'character varying', 'columntype': '1',
     'feildtype': 'VoLTE小区监控预警数据表-天', 'table': 'csem.f_nk_volte_keykpi_cell_d', 'tableName': 'VoLTE小区监控预警数据表-天'},
    {'feild': 'area', 'feildName': '区县', 'datatype': 'character varying', 'columntype': '1',
     'feildtype': 'VoLTE小区监控预警数据表-天', 'table': 'csem.f_nk_volte_keykpi_cell_d', 'tableName': 'VoLTE小区监控预警数据表-天'},
    {'feild': 'nrcell_name', 'feildName': '小区名称', 'datatype': 'character varying', 'columntype': '1',
     'feildtype': 'VoLTE小区监控预警数据表-天', 'table': 'csem.f_nk_volte_keykpi_cell_d', 'tableName': 'VoLTE小区监控预警数据表-天'},
    # VoLTE语音质量指标
    {'feild': 'volte_ul_tunzi_len', 'feildName': 'VoLTE语音上行吞字时长(s)', 'datatype': 'numeric', 'columntype': '1',
     'feildtype': 'VoLTE小区监控预警数据表-天', 'table': 'csem.f_nk_volte_keykpi_cell_d', 'tableName': 'VoLTE小区监控预警数据表-天'},
    {'feild': 'volte_ul_dantong_len', 'feildName': 'VoLTE语音上行单通时长(s)', 'datatype': 'numeric', 'columntype': '1',
     'feildtype': 'VoLTE小区监控预警数据表-天', 'table': 'csem.f_nk_volte_keykpi_cell_d', 'tableName': 'VoLTE小区监控预警数据表-天'},
    {'feild': 'volte_ul_duanxu_len', 'feildName': 'VoLTE语音上行断续时长(s)', 'datatype': 'numeric', 'columntype': '1',
     'feildtype': 'VoLTE小区监控预警数据表-天', 'table': 'csem.f_nk_volte_keykpi_cell_d', 'tableName': 'VoLTE小区监控预警数据表-天'},
    {'feild': 'volte_ul_voice_sum_len', 'feildName': 'VoLTE语音上行总时长(s)', 'datatype': 'numeric', 'columntype': '1',
     'feildtype': 'VoLTE小区监控预警数据表-天', 'table': 'csem.f_nk_volte_keykpi_cell_d', 'tableName': 'VoLTE小区监控预警数据表-天'},
    {'feild': 'volte_ans_voice_call', 'feildName': 'VoLTE通话次数', 'datatype': 'numeric', 'columntype': '1',
     'feildtype': 'VoLTE小区监控预警数据表-天', 'table': 'csem.f_nk_volte_keykpi_cell_d', 'tableName': 'VoLTE小区监控预警数据表-天'},
    # 下行指标（备用）
    {'feild': 'volte_dl_tunzi_len', 'feildName': 'VoLTE语音下行吞字时长(s)', 'datatype': 'numeric', 'columntype': '1',
     'feildtype': 'VoLTE小区监控预警数据表-天', 'table': 'csem.f_nk_volte_keykpi_cell_d', 'tableName': 'VoLTE小区监控预警数据表-天'},
    {'feild': 'volte_dl_dantong_len', 'feildName': 'VoLTE语音下行单通时长(s)', 'datatype': 'numeric', 'columntype': '1',
     'feildtype': 'VoLTE小区监控预警数据表-天', 'table': 'csem.f_nk_volte_keykpi_cell_d', 'tableName': 'VoLTE小区监控预警数据表-天'},
    {'feild': 'volte_dl_duanxu_len', 'feildName': 'VoLTE语音下行断续时长(s)', 'datatype': 'numeric', 'columntype': '1',
     'feildtype': 'VoLTE小区监控预警数据表-天', 'table': 'csem.f_nk_volte_keykpi_cell_d', 'tableName': 'VoLTE小区监控预警数据表-天'},
    {'feild': 'volte_dl_voice_sum_len', 'feildName': 'VoLTE语音下行总时长(s)', 'datatype': 'numeric', 'columntype': '1',
     'feildtype': 'VoLTE小区监控预警数据表-天', 'table': 'csem.f_nk_volte_keykpi_cell_d', 'tableName': 'VoLTE小区监控预警数据表-天'},
]

# ==================== 4G语音小区专用字段配置（EPSFB预警报表） ====================
# 用于4G语音小区预警报表：联合VoLTE预警和EPSFB预警表
EPSFB_4G_VOICE_WARNING_FIELDS = [
    {'feild': 'starttime', 'feildName': '时间', 'datatype': 'timestamp', 'columntype': '1',
     'feildtype': 'EPSFB小区监控预警数据表-天', 'table': 'csem.f_nk_epsfb_keykpi_cell_d', 'tableName': 'EPSFB小区监控预警数据表-天'},
    {'feild': 'city', 'feildName': '地市', 'datatype': 'character varying', 'columntype': '1',
     'feildtype': 'EPSFB小区监控预警数据表-天', 'table': 'csem.f_nk_epsfb_keykpi_cell_d', 'tableName': 'EPSFB小区监控预警数据表-天'},
    {'feild': 'cgi', 'feildName': '小区', 'datatype': 'character varying', 'columntype': '1',
     'feildtype': 'EPSFB小区监控预警数据表-天', 'table': 'csem.f_nk_epsfb_keykpi_cell_d', 'tableName': 'EPSFB小区监控预警数据表-天'},
    {'feild': 'grid', 'feildName': '责任网格', 'datatype': 'character varying', 'columntype': '1',
     'feildtype': 'EPSFB小区监控预警数据表-天', 'table': 'csem.f_nk_epsfb_keykpi_cell_d', 'tableName': 'EPSFB小区监控预警数据表-天'},
    {'feild': 'area', 'feildName': '区县', 'datatype': 'character varying', 'columntype': '1',
     'feildtype': 'EPSFB小区监控预警数据表-天', 'table': 'csem.f_nk_epsfb_keykpi_cell_d', 'tableName': 'EPSFB小区监控预警数据表-天'},
    {'feild': 'nrcell_name', 'feildName': '小区名称', 'datatype': 'character varying', 'columntype': '1',
     'feildtype': 'EPSFB小区监控预警数据表-天', 'table': 'csem.f_nk_epsfb_keykpi_cell_d', 'tableName': 'EPSFB小区监控预警数据表-天'},
    # EPSFB语音质量指标
    {'feild': 'epsfb_ul_tunzi_len', 'feildName': 'EPSFB语音上行吞字时长(s)', 'datatype': 'numeric', 'columntype': '1',
     'feildtype': 'EPSFB小区监控预警数据表-天', 'table': 'csem.f_nk_epsfb_keykpi_cell_d', 'tableName': 'EPSFB小区监控预警数据表-天'},
    {'feild': 'epsfb_ul_dantong_len', 'feildName': 'EPSFB语音上行单通时长(s)', 'datatype': 'numeric', 'columntype': '1',
     'feildtype': 'EPSFB小区监控预警数据表-天', 'table': 'csem.f_nk_epsfb_keykpi_cell_d', 'tableName': 'EPSFB小区监控预警数据表-天'},
    {'feild': 'epsfb_ul_duanxu_len', 'feildName': 'EPSFB语音上行断续时长(s)', 'datatype': 'numeric', 'columntype': '1',
     'feildtype': 'EPSFB小区监控预警数据表-天', 'table': 'csem.f_nk_epsfb_keykpi_cell_d', 'tableName': 'EPSFB小区监控预警数据表-天'},
    {'feild': 'epsfb_ul_voice_sum_len', 'feildName': 'EPSFB语音上行总时长(s)', 'datatype': 'numeric', 'columntype': '1',
     'feildtype': 'EPSFB小区监控预警数据表-天', 'table': 'csem.f_nk_epsfb_keykpi_cell_d', 'tableName': 'EPSFB小区监控预警数据表-天'},
    {'feild': 'epsfb_ans_voice_call', 'feildName': 'EPSFB通话次数', 'datatype': 'numeric', 'columntype': '1',
     'feildtype': 'EPSFB小区监控预警数据表-天', 'table': 'csem.f_nk_epsfb_keykpi_cell_d', 'tableName': 'EPSFB小区监控预警数据表-天'},
    # 下行指标（备用）
    {'feild': 'epsfb_dl_tunzi_len', 'feildName': 'EPSFB语音下行吞字时长(s)', 'datatype': 'numeric', 'columntype': '1',
     'feildtype': 'EPSFB小区监控预警数据表-天', 'table': 'csem.f_nk_epsfb_keykpi_cell_d', 'tableName': 'EPSFB小区监控预警数据表-天'},
    {'feild': 'epsfb_dl_dantong_len', 'feildName': 'EPSFB语音下行单通时长(s)', 'datatype': 'numeric', 'columntype': '1',
     'feildtype': 'EPSFB小区监控预警数据表-天', 'table': 'csem.f_nk_epsfb_keykpi_cell_d', 'tableName': 'EPSFB小区监控预警数据表-天'},
    {'feild': 'epsfb_dl_duanxu_len', 'feildName': 'EPSFB语音下行断续时长(s)', 'datatype': 'numeric', 'columntype': '1',
     'feildtype': 'EPSFB小区监控预警数据表-天', 'table': 'csem.f_nk_epsfb_keykpi_cell_d', 'tableName': 'EPSFB小区监控预警数据表-天'},
    {'feild': 'epsfb_dl_voice_sum_len', 'feildName': 'EPSFB语音下行总时长(s)', 'datatype': 'numeric', 'columntype': '1',
     'feildtype': 'EPSFB小区监控预警数据表-天', 'table': 'csem.f_nk_epsfb_keykpi_cell_d', 'tableName': 'EPSFB小区监控预警数据表-天'},
]

# ==================== 5G小区容量报表字段 ====================
CAPACITY_5G_FIELDS = [
    {'feild': 'starttime', 'feildName': '记录开始时间', 'datatype': 'character varying', 'columntype': '1',
     'feildtype': '5G小区容量报表 - 天粒度', 'table': 'appdbv3.a_adhoc_capacity_nr_nrcell_d', 'tableName': '5G小区容量报表 - 天粒度'},
    {'feild': 'endtime', 'feildName': '记录结束时间', 'datatype': 'character varying', 'columntype': '1',
     'feildtype': '5G小区容量报表 - 天粒度', 'table': 'appdbv3.a_adhoc_capacity_nr_nrcell_d', 'tableName': '5G小区容量报表 - 天粒度'},
    {'feild': 'city', 'feildName': '地市', 'datatype': 'character varying', 'columntype': '1',
     'feildtype': '5G小区容量报表 - 天粒度', 'table': 'appdbv3.a_adhoc_capacity_nr_nrcell_d', 'tableName': '5G小区容量报表 - 天粒度'},
    {'feild': 'grid', 'feildName': '责任网格', 'datatype': 'character varying', 'columntype': '1',
     'feildtype': '5G小区容量报表 - 天粒度', 'table': 'appdbv3.a_adhoc_capacity_nr_nrcell_d', 'tableName': '5G小区容量报表 - 天粒度'},
    {'feild': 'nrcell_name', 'feildName': '小区名称', 'datatype': 'character varying', 'columntype': '2',
     'feildtype': '5G小区容量报表 - 天粒度', 'table': 'appdbv3.a_adhoc_capacity_nr_nrcell_d', 'tableName': '5G小区容量报表 - 天粒度'},
    {'feild': 'ncgi', 'feildName': 'NCGI', 'datatype': 'character varying', 'columntype': '1',
     'feildtype': '5G小区容量报表 - 天粒度', 'table': 'appdbv3.a_adhoc_capacity_nr_nrcell_d', 'tableName': '5G小区容量报表 - 天粒度'},
    {'feild': 'busy_hour', 'feildName': '忙时', 'datatype': 'timestamp', 'columntype': '1',
     'feildtype': '5G小区容量报表 - 天粒度', 'table': 'appdbv3.a_adhoc_capacity_nr_nrcell_d', 'tableName': '5G小区容量报表 - 天粒度'},
    {'feild': 'state', 'feildName': '网元状态', 'datatype': 'character varying', 'columntype': '1',
     'feildtype': '5G小区容量报表 - 天粒度', 'table': 'appdbv3.a_adhoc_capacity_nr_nrcell_d', 'tableName': '5G小区容量报表 - 天粒度'},
    {'feild': 'vendor', 'feildName': '厂家', 'datatype': 'character varying', 'columntype': '1',
     'feildtype': '5G小区容量报表 - 天粒度', 'table': 'appdbv3.a_adhoc_capacity_nr_nrcell_d', 'tableName': '5G小区容量报表 - 天粒度'},
    {'feild': 'frequency_band_detail', 'feildName': '详细使用频段', 'datatype': 'character varying', 'columntype': '1',
     'feildtype': '5G小区容量报表 - 天粒度', 'table': 'appdbv3.a_adhoc_capacity_nr_nrcell_d', 'tableName': '5G小区容量报表 - 天粒度'},
    {'feild': 'freq', 'feildName': '使用频段', 'datatype': 'character varying', 'columntype': '1',
     'feildtype': '5G小区容量报表 - 天粒度', 'table': 'appdbv3.a_adhoc_capacity_nr_nrcell_d', 'tableName': '5G小区容量报表 - 天粒度'},
    {'feild': 'cover_type', 'feildName': '覆盖类型', 'datatype': 'character varying', 'columntype': '1',
     'feildtype': '5G小区容量报表 - 天粒度', 'table': 'appdbv3.a_adhoc_capacity_nr_nrcell_d', 'tableName': '5G小区容量报表 - 天粒度'},
    {'feild': 'cover_scene', 'feildName': '覆盖场景', 'datatype': 'character varying', 'columntype': '1',
     'feildtype': '5G小区容量报表 - 天粒度', 'table': 'appdbv3.a_adhoc_capacity_nr_nrcell_d', 'tableName': '5G小区容量报表 - 天粒度'},
    {'feild': 'is_remote', 'feildName': '是否拉远', 'datatype': 'boolean', 'columntype': '1',
     'feildtype': '5G小区容量报表 - 天粒度', 'table': 'appdbv3.a_adhoc_capacity_nr_nrcell_d', 'tableName': '5G小区容量报表 - 天粒度'},
    {'feild': 'station_name', 'feildName': '所属基站', 'datatype': 'character varying', 'columntype': '1',
     'feildtype': '5G小区容量报表 - 天粒度', 'table': 'appdbv3.a_adhoc_capacity_nr_nrcell_d', 'tableName': '5G小区容量报表 - 天粒度'},
    {'feild': 'longitude', 'feildName': '经度', 'datatype': 'decimal', 'columntype': '1',
     'feildtype': '5G小区容量报表 - 天粒度', 'table': 'appdbv3.a_adhoc_capacity_nr_nrcell_d', 'tableName': '5G小区容量报表 - 天粒度'},
    {'feild': 'latitude', 'feildName': '纬度', 'datatype': 'decimal', 'columntype': '1',
     'feildtype': '5G小区容量报表 - 天粒度', 'table': 'appdbv3.a_adhoc_capacity_nr_nrcell_d', 'tableName': '5G小区容量报表 - 天粒度'},
    {'feild': 'bh_pdcchcceoccupancyrate', 'feildName': '忙时PDCCH信道CCE占用率(%)', 'datatype': 'decimal', 'columntype': '1',
     'feildtype': '5G小区容量报表 - 天粒度', 'table': 'appdbv3.a_adhoc_capacity_nr_nrcell_d', 'tableName': '5G小区容量报表 - 天粒度'},
    {'feild': 'bh_prbassnrateul', 'feildName': '忙时上行PRB平均利用率(%)', 'datatype': 'decimal', 'columntype': '1',
     'feildtype': '5G小区容量报表 - 天粒度', 'table': 'appdbv3.a_adhoc_capacity_nr_nrcell_d', 'tableName': '5G小区容量报表 - 天粒度'},
    {'feild': 'bh_prbassnratedl', 'feildName': '忙时下行PRB平均利用率(%)', 'datatype': 'decimal', 'columntype': '1',
     'feildtype': '5G小区容量报表 - 天粒度', 'table': 'appdbv3.a_adhoc_capacity_nr_nrcell_d', 'tableName': '5G小区容量报表 - 天粒度'},
    {'feild': 'bh_cellprbrate', 'feildName': '忙时小区PRB利用率', 'datatype': 'character varying', 'columntype': '1',
     'feildtype': '5G小区容量报表 - 天粒度', 'table': 'appdbv3.a_adhoc_capacity_nr_nrcell_d', 'tableName': '5G小区容量报表 - 天粒度'},
    {'feild': 'rlc_upoctudl', 'feildName': '日RLC层上下行总流量(G)', 'datatype': 'decimal', 'columntype': '1',
     'feildtype': '5G小区容量报表 - 天粒度', 'table': 'appdbv3.a_adhoc_capacity_nr_nrcell_d', 'tableName': '5G小区容量报表 - 天粒度'},
    {'feild': 'pdcp_upoctudl', 'feildName': '日PDCP层上下行总流量(G)', 'datatype': 'decimal', 'columntype': '1',
     'feildtype': '5G小区容量报表 - 天粒度', 'table': 'appdbv3.a_adhoc_capacity_nr_nrcell_d', 'tableName': '5G小区容量报表 - 天粒度'},
    {'feild': 'bh_rrc_connmean', 'feildName': 'RRC连接平均数-忙时', 'datatype': 'character varying', 'columntype': '2',
     'feildtype': '5G小区容量报表 - 天粒度', 'table': 'appdbv3.a_adhoc_capacity_nr_nrcell_d', 'tableName': '5G小区容量报表 - 天粒度'},
    {'feild': 'bh_rrc_connmax', 'feildName': 'RRC连接最大数-忙时', 'datatype': 'character varying', 'columntype': '2',
     'feildtype': '5G小区容量报表 - 天粒度', 'table': 'appdbv3.a_adhoc_capacity_nr_nrcell_d', 'tableName': '5G小区容量报表 - 天粒度'},
    {'feild': 'is_highload', 'feildName': '是否高负荷待扩容小区', 'datatype': 'boolean', 'columntype': '1',
     'feildtype': '5G小区容量报表 - 天粒度', 'table': 'appdbv3.a_adhoc_capacity_nr_nrcell_d', 'tableName': '5G小区容量报表 - 天粒度'},
    {'feild': 'micro_grid', 'feildName': '微网格标识', 'datatype': 'character varying', 'columntype': '1',
     'feildtype': '5G小区容量报表 - 天粒度', 'table': 'appdbv3.a_adhoc_capacity_nr_nrcell_d', 'tableName': '5G小区容量报表 - 天粒度'},
]

# ==================== 重要场景-天报表字段 ====================
IMPORTANT_SCENE_FIELDS = [
    {'feild': 'starttime', 'feildName': '记录开始时间', 'datatype': 'timestamp', 'columntype': '1',
     'feildtype': '重要场景-小区天', 'table': 'appdbv3.a_overview_ispm_lte_cell_d', 'tableName': '[管理视图]重要场景-小区天粒度'},
    {'feild': 'endtime', 'feildName': '记录结束时间', 'datatype': 'timestamp', 'columntype': '1',
     'feildtype': '重要场景-小区天', 'table': 'appdbv3.a_overview_ispm_lte_cell_d', 'tableName': '[管理视图]重要场景-小区天粒度'},
    {'feild': 'city', 'feildName': '所属地市', 'datatype': 'character varying', 'columntype': '1',
     'feildtype': '重要场景-小区天', 'table': 'appdbv3.a_overview_ispm_lte_cell_d', 'tableName': '[管理视图]重要场景-小区天粒度'},
    {'feild': 'cgi', 'feildName': 'CGI', 'datatype': 'character varying', 'columntype': '1',
     'feildtype': '重要场景-小区天', 'table': 'appdbv3.a_overview_ispm_lte_cell_d', 'tableName': '[管理视图]重要场景-小区天粒度'},
    {'feild': 'busy_hour', 'feildName': '自忙时', 'datatype': 'timestamp', 'columntype': '1',
     'feildtype': '重要场景-小区天', 'table': 'appdbv3.a_overview_ispm_lte_cell_d', 'tableName': '[管理视图]重要场景-小区天粒度'},
    {'feild': 'freq_name', 'feildName': '详细频段', 'datatype': 'character varying', 'columntype': '1',
     'feildtype': '重要场景-小区天', 'table': 'appdbv3.a_overview_ispm_lte_cell_d', 'tableName': '[管理视图]重要场景-小区天粒度'},
    {'feild': 'cell_name', 'feildName': '小区名称', 'datatype': 'character varying', 'columntype': '1',
     'feildtype': '重要场景-小区天', 'table': 'appdbv3.a_overview_ispm_lte_cell_d', 'tableName': '[管理视图]重要场景-小区天粒度'},
    {'feild': 'state', 'feildName': '网元状态', 'datatype': 'character varying', 'columntype': '1',
     'feildtype': '重要场景-小区天', 'table': 'appdbv3.a_overview_ispm_lte_cell_d', 'tableName': '[管理视图]重要场景-小区天粒度'},
    {'feild': 'scene', 'feildName': '场景', 'datatype': 'character varying', 'columntype': '1',
     'feildtype': '重要场景-小区天', 'table': 'appdbv3.a_overview_ispm_lte_cell_d', 'tableName': '[管理视图]重要场景-小区天粒度'},
    {'feild': 'scene_name', 'feildName': '场景具体名称', 'datatype': 'character varying', 'columntype': '1',
     'feildtype': '重要场景-小区天', 'table': 'appdbv3.a_overview_ispm_lte_cell_d', 'tableName': '[管理视图]重要场景-小区天粒度'},
    {'feild': 'upoctudl', 'feildName': '日4G流量（GB）', 'datatype': 'decimal', 'columntype': '1',
     'feildtype': '重要场景-小区天', 'table': 'appdbv3.a_overview_ispm_lte_cell_d', 'tableName': '[管理视图]重要场景-小区天粒度'},
    {'feild': 'ul_prbuse_rate_max', 'feildName': '日峰值上行PRB平均利用率', 'datatype': 'decimal', 'columntype': '1',
     'feildtype': '重要场景-小区天', 'table': 'appdbv3.a_overview_ispm_lte_cell_d', 'tableName': '[管理视图]重要场景-小区天粒度'},
    {'feild': 'dl_prbuse_rate_max', 'feildName': '日峰值下行PRB平均利用率', 'datatype': 'decimal', 'columntype': '1',
     'feildtype': '重要场景-小区天', 'table': 'appdbv3.a_overview_ispm_lte_cell_d', 'tableName': '[管理视图]重要场景-小区天粒度'},
    {'feild': 'pdcchcceutilratio_max', 'feildName': '日峰值PDCCH信道CCE占用率', 'datatype': 'decimal', 'columntype': '1',
     'feildtype': '重要场景-小区天', 'table': 'appdbv3.a_overview_ispm_lte_cell_d', 'tableName': '[管理视图]重要场景-小区天粒度'},
    {'feild': 'bh_effectiveconnmax', 'feildName': '自忙时有效RRC连接最大数', 'datatype': 'integer', 'columntype': '1',
     'feildtype': '重要场景-小区天', 'table': 'appdbv3.a_overview_ispm_lte_cell_d', 'tableName': '[管理视图]重要场景-小区天粒度'},
    {'feild': 'bh_connmax', 'feildName': '自忙时RRC连接最大数', 'datatype': 'integer', 'columntype': '1',
     'feildtype': '重要场景-小区天', 'table': 'appdbv3.a_overview_ispm_lte_cell_d', 'tableName': '[管理视图]重要场景-小区天粒度'},
    {'feild': 'bh_effectiveconnmean', 'feildName': '自忙时有效RRC连接平均数', 'datatype': 'decimal', 'columntype': '1',
     'feildtype': '重要场景-小区天', 'table': 'appdbv3.a_overview_ispm_lte_cell_d', 'tableName': '[管理视图]重要场景-小区天粒度'},
    {'feild': 'bh_upoctul', 'feildName': '自忙时空口上行业务字节数', 'datatype': 'decimal', 'columntype': '1',
     'feildtype': '重要场景-小区天', 'table': 'appdbv3.a_overview_ispm_lte_cell_d', 'tableName': '[管理视图]重要场景-小区天粒度'},
    {'feild': 'bh_upoctdl', 'feildName': '自忙时空口下行业务字节数', 'datatype': 'decimal', 'columntype': '1',
     'feildtype': '重要场景-小区天', 'table': 'appdbv3.a_overview_ispm_lte_cell_d', 'tableName': '[管理视图]重要场景-小区天粒度'},
    {'feild': 'bh_ul_prbuse_rate', 'feildName': '自忙时上行PRB平均利用率', 'datatype': 'decimal', 'columntype': '1',
     'feildtype': '重要场景-小区天', 'table': 'appdbv3.a_overview_ispm_lte_cell_d', 'tableName': '[管理视图]重要场景-小区天粒度'},
    {'feild': 'bh_dl_prbuse_rate', 'feildName': '自忙时下行PRB平均利用率', 'datatype': 'decimal', 'columntype': '1',
     'feildtype': '重要场景-小区天', 'table': 'appdbv3.a_overview_ispm_lte_cell_d', 'tableName': '[管理视图]重要场景-小区天粒度'},
    {'feild': 'bh_pdcchcceutilratio', 'feildName': '自忙时PDCCH信道CCE占用率', 'datatype': 'decimal', 'columntype': '1',
     'feildtype': '重要场景-小区天', 'table': 'appdbv3.a_overview_ispm_lte_cell_d', 'tableName': '[管理视图]重要场景-小区天粒度'},
    {'feild': 'radio_succ_rate', 'feildName': '无线接通率', 'datatype': 'decimal', 'columntype': '1',
     'feildtype': '重要场景-小区天', 'table': 'appdbv3.a_overview_ispm_lte_cell_d', 'tableName': '[管理视图]重要场景-小区天粒度'},
    {'feild': 'radio_drop_rate_cell', 'feildName': '无线掉线率(小区级)', 'datatype': 'decimal', 'columntype': '1',
     'feildtype': '重要场景-小区天', 'table': 'appdbv3.a_overview_ispm_lte_cell_d', 'tableName': '[管理视图]重要场景-小区天粒度'},
    {'feild': 'call_connect_rate', 'feildName': '呼叫接通率(MTC+MOC)', 'datatype': 'decimal', 'columntype': '1',
     'feildtype': '重要场景-小区天', 'table': 'appdbv3.a_overview_ispm_lte_cell_d', 'tableName': '[管理视图]重要场景-小区天粒度'},
    {'feild': 'volte_drop_rate', 'feildName': 'VOLTE掉话率', 'datatype': 'decimal', 'columntype': '1',
     'feildtype': '重要场景-小区天', 'table': 'appdbv3.a_overview_ispm_lte_cell_d', 'tableName': '[管理视图]重要场景-小区天粒度'},
    {'feild': 'esrvcc_ho_succ_rate', 'feildName': 'ESRVCC切换成功率', 'datatype': 'decimal', 'columntype': '1',
     'feildtype': '重要场景-小区天', 'table': 'appdbv3.a_overview_ispm_lte_cell_d', 'tableName': '[管理视图]重要场景-小区天粒度'},
    {'feild': 'volte_voice_traffic', 'feildName': 'VOLTE语音话务量', 'datatype': 'decimal', 'columntype': '1',
     'feildtype': '重要场景-小区天', 'table': 'appdbv3.a_overview_ispm_lte_cell_d', 'tableName': '[管理视图]重要场景-小区天粒度'},
    {'feild': 'bh_avg_erab', 'feildName': '小区自忙时平均E-RAB流量', 'datatype': 'decimal', 'columntype': '1',
     'feildtype': '重要场景-小区天', 'table': 'appdbv3.a_overview_ispm_lte_cell_d', 'tableName': '[管理视图]重要场景-小区天粒度'},
    {'feild': 'bh_peak_use_rate', 'feildName': '自忙时峰值利用率', 'datatype': 'decimal', 'columntype': '1',
     'feildtype': '重要场景-小区天', 'table': 'appdbv3.a_overview_ispm_lte_cell_d', 'tableName': '[管理视图]重要场景-小区天粒度'},
    {'feild': 'bh_nbrsuccestab', 'feildName': '自忙时E-RAB建立成功数', 'datatype': 'integer', 'columntype': '1',
     'feildtype': '重要场景-小区天', 'table': 'appdbv3.a_overview_ispm_lte_cell_d', 'tableName': '[管理视图]重要场景-小区天粒度'},
    {'feild': 'is_highflow', 'feildName': '是否高流量预警小区（集团高负荷预警）', 'datatype': 'character varying', 'columntype': '1',
     'feildtype': '重要场景-小区天', 'table': 'appdbv3.a_overview_ispm_lte_cell_d', 'tableName': '[管理视图]重要场景-小区天粒度'},
    {'feild': 'is_highload', 'feildName': '是否高负荷待扩容小区', 'datatype': 'character varying', 'columntype': '1',
     'feildtype': '重要场景-小区天', 'table': 'appdbv3.a_overview_ispm_lte_cell_d', 'tableName': '[管理视图]重要场景-小区天粒度'},
    {'feild': 'vendor', 'feildName': '设备厂家', 'datatype': 'character varying', 'columntype': '1',
     'feildtype': '重要场景-小区天', 'table': 'appdbv3.a_overview_ispm_lte_cell_d', 'tableName': '[管理视图]重要场景-小区天粒度'},
    {'feild': 'freq', 'feildName': '使用频段', 'datatype': 'character varying', 'columntype': '1',
     'feildtype': '重要场景-小区天', 'table': 'appdbv3.a_overview_ispm_lte_cell_d', 'tableName': '[管理视图]重要场景-小区天粒度'},
    {'feild': 'bandwidth', 'feildName': '小区带宽', 'datatype': 'character varying', 'columntype': '1',
     'feildtype': '重要场景-小区天', 'table': 'appdbv3.a_overview_ispm_lte_cell_d', 'tableName': '[管理视图]重要场景-小区天粒度'},
    {'feild': 'is_remote', 'feildName': '是否拉远', 'datatype': 'character varying', 'columntype': '1',
     'feildtype': '重要场景-小区天', 'table': 'appdbv3.a_overview_ispm_lte_cell_d', 'tableName': '[管理视图]重要场景-小区天粒度'},
    {'feild': 'station_name', 'feildName': '所属站点名称', 'datatype': 'character varying', 'columntype': '1',
     'feildtype': '重要场景-小区天', 'table': 'appdbv3.a_overview_ispm_lte_cell_d', 'tableName': '[管理视图]重要场景-小区天粒度'},
    {'feild': 'longitude', 'feildName': '经度', 'datatype': 'character varying', 'columntype': '1',
     'feildtype': '重要场景-小区天', 'table': 'appdbv3.a_overview_ispm_lte_cell_d', 'tableName': '[管理视图]重要场景-小区天粒度'},
    {'feild': 'latitude', 'feildName': '维度', 'datatype': 'character varying', 'columntype': '1',
     'feildtype': '重要场景-小区天', 'table': 'appdbv3.a_overview_ispm_lte_cell_d', 'tableName': '[管理视图]重要场景-小区天粒度'},
    {'feild': 'cover', 'feildName': '覆盖类型', 'datatype': 'character varying', 'columntype': '1',
     'feildtype': '重要场景-小区天', 'table': 'appdbv3.a_overview_ispm_lte_cell_d', 'tableName': '[管理视图]重要场景-小区天粒度'},
    {'feild': 'coverlayer', 'feildName': '覆盖层标识', 'datatype': 'character varying', 'columntype': '1',
     'feildtype': '重要场景-小区天', 'table': 'appdbv3.a_overview_ispm_lte_cell_d', 'tableName': '[管理视图]重要场景-小区天粒度'},
    {'feild': 'capacitylayer', 'feildName': '容量层标识', 'datatype': 'character varying', 'columntype': '1',
     'feildtype': '重要场景-小区天', 'table': 'appdbv3.a_overview_ispm_lte_cell_d', 'tableName': '[管理视图]重要场景-小区天粒度'},
]

# ==================== 5G小区工参报表字段 ====================
GONGCAN_5G_FIELDS = [
    {'feild': 'starttime', 'feildName': '数据时间', 'datatype': 'character varying', 'columntype': '1',
     'feildtype': '5G小区工参', 'table': 'appdbv3.a_common_cfg_nr_cellant_d', 'tableName': '5G小区工参'},
    {'feild': 'nrcell_name', 'feildName': '小区名称', 'datatype': 'character varying', 'columntype': '2',
     'feildtype': '5G小区工参', 'table': 'appdbv3.a_common_cfg_nr_cellant_d', 'tableName': '5G小区工参'},
    {'feild': 'ncgi', 'feildName': 'NCGI', 'datatype': 'character varying', 'columntype': '1',
     'feildtype': '5G小区工参', 'table': 'appdbv3.a_common_cfg_nr_cellant_d', 'tableName': '5G小区工参'},
    {'feild': 'city', 'feildName': '地市', 'datatype': 'character varying', 'columntype': '1',
     'feildtype': '5G小区工参', 'table': 'appdbv3.a_common_cfg_nr_cellant_d', 'tableName': '5G小区工参'},
    {'feild': 'vendor', 'feildName': '设备厂家', 'datatype': 'character varying', 'columntype': '1',
     'feildtype': '5G小区工参', 'table': 'appdbv3.a_common_cfg_nr_cellant_d', 'tableName': '5G小区工参'},
    {'feild': 'station_name', 'feildName': '所属基站', 'datatype': 'character varying', 'columntype': '1',
     'feildtype': '5G小区工参', 'table': 'appdbv3.a_common_cfg_nr_cellant_d', 'tableName': '5G小区工参'},
    {'feild': 'bandwidth', 'feildName': '小区带宽(MHz)', 'datatype': 'character varying', 'columntype': '1',
     'feildtype': '5G小区工参', 'table': 'appdbv3.a_common_cfg_nr_cellant_d', 'tableName': '5G小区工参'},
    {'feild': 'freq', 'feildName': 'ARFCN/ARFCN-ND', 'datatype': 'character varying', 'columntype': '1',
     'feildtype': '5G小区工参', 'table': 'appdbv3.a_common_cfg_nr_cellant_d', 'tableName': '5G小区工参'},
    {'feild': 'tac', 'feildName': 'TAC', 'datatype': 'character varying', 'columntype': '1',
     'feildtype': '5G小区工参', 'table': 'appdbv3.a_common_cfg_nr_cellant_d', 'tableName': '5G小区工参'},
    {'feild': 'pci', 'feildName': 'PCI', 'datatype': 'character varying', 'columntype': '1',
     'feildtype': '5G小区工参', 'table': 'appdbv3.a_common_cfg_nr_cellant_d', 'tableName': '5G小区工参'},
    {'feild': 'ssb_freq', 'feildName': 'SSB频点', 'datatype': 'character varying', 'columntype': '1',
     'feildtype': '5G小区工参', 'table': 'appdbv3.a_common_cfg_nr_cellant_d', 'tableName': '5G小区工参'},
    {'feild': 'ssb_period', 'feildName': 'SSB周期', 'datatype': 'character varying', 'columntype': '1',
     'feildtype': '5G小区工参', 'table': 'appdbv3.a_common_cfg_nr_cellant_d', 'tableName': '5G小区工参'},
    {'feild': 'ssb_offset', 'feildName': 'SSB偏移', 'datatype': 'character varying', 'columntype': '1',
     'feildtype': '5G小区工参', 'table': 'appdbv3.a_common_cfg_nr_cellant_d', 'tableName': '5G小区工参'},
    {'feild': 'longitude', 'feildName': '经度', 'datatype': 'character varying', 'columntype': '1',
     'feildtype': '5G小区工参', 'table': 'appdbv3.a_common_cfg_nr_cellant_d', 'tableName': '5G小区工参'},
    {'feild': 'latitude', 'feildName': '纬度', 'datatype': 'character varying', 'columntype': '1',
     'feildtype': '5G小区工参', 'table': 'appdbv3.a_common_cfg_nr_cellant_d', 'tableName': '5G小区工参'},
    {'feild': 'azimuth', 'feildName': '方位角(度)', 'datatype': 'character varying', 'columntype': '1',
     'feildtype': '5G小区工参', 'table': 'appdbv3.a_common_cfg_nr_cellant_d', 'tableName': '5G小区工参'},
    {'feild': 'electrical_tilt', 'feildName': '电子下倾角(度)', 'datatype': 'character varying', 'columntype': '1',
     'feildtype': '5G小区工参', 'table': 'appdbv3.a_common_cfg_nr_cellant_d', 'tableName': '5G小区工参'},
    {'feild': 'mechanical_tilt', 'feildName': '机械下倾角(度)', 'datatype': 'character varying', 'columntype': '1',
     'feildtype': '5G小区工参', 'table': 'appdbv3.a_common_cfg_nr_cellant_d', 'tableName': '5G小区工参'},
    {'feild': 'total_tilt', 'feildName': '总下倾角(度)', 'datatype': 'character varying', 'columntype': '1',
     'feildtype': '5G小区工参', 'table': 'appdbv3.a_common_cfg_nr_cellant_d', 'tableName': '5G小区工参'},
    {'feild': 'cover_type', 'feildName': '覆盖类型', 'datatype': 'character varying', 'columntype': '1',
     'feildtype': '5G小区工参', 'table': 'appdbv3.a_common_cfg_nr_cellant_d', 'tableName': '5G小区工参'},
    {'feild': 'txrx_mode', 'feildName': '收发模式', 'datatype': 'character varying', 'columntype': '1',
     'feildtype': '5G小区工参', 'table': 'appdbv3.a_common_cfg_nr_cellant_d', 'tableName': '5G小区工参'},
    {'feild': 'max_tx_power', 'feildName': '最大发射功率(dBm)', 'datatype': 'character varying', 'columntype': '1',
     'feildtype': '5G小区工参', 'table': 'appdbv3.a_common_cfg_nr_cellant_d', 'tableName': '5G小区工参'},
]

# ==================== 4G小区工参报表字段 ====================
GONGCAN_4G_FIELDS = [
    {'feild': 'starttime', 'feildName': '数据时间', 'datatype': 'character varying', 'columntype': '1',
     'feildtype': '4G小区工参', 'table': 'appdbv3.v_a_common_cfg_lte_cellant_d', 'tableName': '4G小区工参'},
    {'feild': 'cell_name', 'feildName': '小区名称', 'datatype': 'character varying', 'columntype': '2',
     'feildtype': '4G小区工参', 'table': 'appdbv3.v_a_common_cfg_lte_cellant_d', 'tableName': '4G小区工参'},
    {'feild': 'cgi', 'feildName': 'CGI', 'datatype': 'character varying', 'columntype': '1',
     'feildtype': '4G小区工参', 'table': 'appdbv3.v_a_common_cfg_lte_cellant_d', 'tableName': '4G小区工参'},
    {'feild': 'city', 'feildName': '地市', 'datatype': 'character varying', 'columntype': '1',
     'feildtype': '4G小区工参', 'table': 'appdbv3.v_a_common_cfg_lte_cellant_d', 'tableName': '4G小区工参'},
    {'feild': 'vendor', 'feildName': '设备厂家', 'datatype': 'character varying', 'columntype': '1',
     'feildtype': '4G小区工参', 'table': 'appdbv3.v_a_common_cfg_lte_cellant_d', 'tableName': '4G小区工参'},
    {'feild': 'station_name', 'feildName': '所属基站', 'datatype': 'character varying', 'columntype': '1',
     'feildtype': '4G小区工参', 'table': 'appdbv3.v_a_common_cfg_lte_cellant_d', 'tableName': '4G小区工参'},
    {'feild': 'earfcn', 'feildName': 'EARFCN', 'datatype': 'character varying', 'columntype': '1',
     'feildtype': '4G小区工参', 'table': 'appdbv3.v_a_common_cfg_lte_cellant_d', 'tableName': '4G小区工参'},
    {'feild': 'freq', 'feildName': '频段', 'datatype': 'character varying', 'columntype': '1',
     'feildtype': '4G小区工参', 'table': 'appdbv3.v_a_common_cfg_lte_cellant_d', 'tableName': '4G小区工参'},
    {'feild': 'bandwidth', 'feildName': '小区带宽', 'datatype': 'character varying', 'columntype': '1',
     'feildtype': '4G小区工参', 'table': 'appdbv3.v_a_common_cfg_lte_cellant_d', 'tableName': '4G小区工参'},
    {'feild': 'pci', 'feildName': 'PCI', 'datatype': 'character varying', 'columntype': '1',
     'feildtype': '4G小区工参', 'table': 'appdbv3.v_a_common_cfg_lte_cellant_d', 'tableName': '4G小区工参'},
    {'feild': 'tac', 'feildName': 'TAC', 'datatype': 'character varying', 'columntype': '1',
     'feildtype': '4G小区工参', 'table': 'appdbv3.v_a_common_cfg_lte_cellant_d', 'tableName': '4G小区工参'},
    {'feild': 'longitude', 'feildName': '经度', 'datatype': 'character varying', 'columntype': '1',
     'feildtype': '4G小区工参', 'table': 'appdbv3.v_a_common_cfg_lte_cellant_d', 'tableName': '4G小区工参'},
    {'feild': 'latitude', 'feildName': '纬度', 'datatype': 'character varying', 'columntype': '1',
     'feildtype': '4G小区工参', 'table': 'appdbv3.v_a_common_cfg_lte_cellant_d', 'tableName': '4G小区工参'},
    {'feild': 'azimuth', 'feildName': '方位角', 'datatype': 'character varying', 'columntype': '1',
     'feildtype': '4G小区工参', 'table': 'appdbv3.v_a_common_cfg_lte_cellant_d', 'tableName': '4G小区工参'},
    {'feild': 'electrical_tilt', 'feildName': '电子下倾角', 'datatype': 'character varying', 'columntype': '1',
     'feildtype': '4G小区工参', 'table': 'appdbv3.v_a_common_cfg_lte_cellant_d', 'tableName': '4G小区工参'},
    {'feild': 'mechanical_tilt', 'feildName': '机械下倾角', 'datatype': 'character varying', 'columntype': '1',
     'feildtype': '4G小区工参', 'table': 'appdbv3.v_a_common_cfg_lte_cellant_d', 'tableName': '4G小区工参'},
    {'feild': 'cover_type', 'feildName': '覆盖类型', 'datatype': 'character varying', 'columntype': '1',
     'feildtype': '4G小区工参', 'table': 'appdbv3.v_a_common_cfg_lte_cellant_d', 'tableName': '4G小区工参'},
    {'feild': 'txrx_mode', 'feildName': '收发模式', 'datatype': 'character varying', 'columntype': '1',
     'feildtype': '4G小区工参', 'table': 'appdbv3.v_a_common_cfg_lte_cellant_d', 'tableName': '4G小区工参'},
    {'feild': 'max_tx_power', 'feildName': '最大发射功率', 'datatype': 'character varying', 'columntype': '1',
     'feildtype': '4G小区工参', 'table': 'appdbv3.v_a_common_cfg_lte_cellant_d', 'tableName': '4G小区工参'},
    {'feild': 'rs_power', 'feildName': 'RS功率', 'datatype': 'character varying', 'columntype': '1',
     'feildtype': '4G小区工参', 'table': 'appdbv3.v_a_common_cfg_lte_cellant_d', 'tableName': '4G小区工参'},
]

# ==================== 5G MR覆盖报表字段 ====================
# 基于HAR抓包获取的真实字段配置
MR_5G_FIELDS = [
    {'feild': 'starttime', 'feildName': '记录开始时间', 'datatype': 'character varying', 'columntype': '1',
     'feildtype': '5GMR覆盖-小区天', 'table': 'appdbv3.a_common_mro_scssrsrp_nr_nrcell', 'tableName': '5GMR覆盖-小区天'},
    {'feild': 'ncgi', 'feildName': '小区NCGI', 'datatype': 'character varying', 'columntype': '1',
     'feildtype': '5GMR覆盖-小区天', 'table': 'appdbv3.a_common_mro_scssrsrp_nr_nrcell', 'tableName': '5GMR覆盖-小区天'},
    {'feild': 'nrcell_name', 'feildName': '小区名称', 'datatype': 'character varying', 'columntype': '1',
     'feildtype': '5GMR覆盖-小区天', 'table': 'appdbv3.a_common_mro_scssrsrp_nr_nrcell', 'tableName': '5GMR覆盖-小区天'},
    {'feild': 'nr_rsrp_count', 'feildName': '移动RSRP采样的总采样点', 'datatype': 'character varying', 'columntype': '1',
     'feildtype': '5GMR覆盖-小区天', 'table': 'appdbv3.a_common_mro_scssrsrp_nr_nrcell', 'tableName': '5GMR覆盖-小区天'},
    {'feild': 'nr_rsrp_gt_f110', 'feildName': '移动RSRP采样强于-110采样点', 'datatype': 'character varying', 'columntype': '1',
     'feildtype': '5GMR覆盖-小区天', 'table': 'appdbv3.a_common_mro_scssrsrp_nr_nrcell', 'tableName': '5GMR覆盖-小区天'},
    {'feild': 'nr_rsrp_rate', 'feildName': '移动RSRP采样强于-110覆盖率(%)', 'datatype': 'character varying', 'columntype': '1',
     'feildtype': '5GMR覆盖-小区天', 'table': 'appdbv3.a_common_mro_scssrsrp_nr_nrcell', 'tableName': '5GMR覆盖-小区天'},
    {'feild': 'mro_yd_rsrp_avg', 'feildName': '移动平均RSRP', 'datatype': 'character varying', 'columntype': '1',
     'feildtype': '5GMR覆盖-小区天', 'table': 'appdbv3.a_common_mro_scssrsrp_nr_nrcell', 'tableName': '5GMR覆盖-小区天'},
    {'feild': 'mro_lt_rsrp_avg', 'feildName': '联通平均RSRP', 'datatype': 'character varying', 'columntype': '1',
     'feildtype': '5GMR覆盖-小区天', 'table': 'appdbv3.a_common_mro_scssrsrp_nr_nrcell', 'tableName': '5GMR覆盖-小区天'},
    {'feild': 'mro_dx_rsrp_avg', 'feildName': '电信平均RSRP', 'datatype': 'character varying', 'columntype': '1',
     'feildtype': '5GMR覆盖-小区天', 'table': 'appdbv3.a_common_mro_scssrsrp_nr_nrcell', 'tableName': '5GMR覆盖-小区天'},
    {'feild': 'mro_rh_rsrp_avg', 'feildName': '融合竞对平均RSRP', 'datatype': 'character varying', 'columntype': '1',
     'feildtype': '5GMR覆盖-小区天', 'table': 'appdbv3.a_common_mro_scssrsrp_nr_nrcell', 'tableName': '5GMR覆盖-小区天'},
    {'feild': 'mro_rh_all_count', 'feildName': '移动融合竞对均有RSRP采样的总采样点', 'datatype': 'character varying', 'columntype': '1',
     'feildtype': '5GMR覆盖-小区天', 'table': 'appdbv3.a_common_mro_scssrsrp_nr_nrcell', 'tableName': '5GMR覆盖-小区天'},
    {'feild': 'mro_rh_yd_f110_count', 'feildName': '采集到融合频点是移动大于等于-110采样点', 'datatype': 'character varying', 'columntype': '1',
     'feildtype': '5GMR覆盖-小区天', 'table': 'appdbv3.a_common_mro_scssrsrp_nr_nrcell', 'tableName': '5GMR覆盖-小区天'},
    {'feild': 'mro_rh_f110_count', 'feildName': '移动融合竞对均有RSRP采样的竞对强于-110采样点', 'datatype': 'character varying', 'columntype': '1',
     'feildtype': '5GMR覆盖-小区天', 'table': 'appdbv3.a_common_mro_scssrsrp_nr_nrcell', 'tableName': '5GMR覆盖-小区天'},
    {'feild': 'mro_overlap_rsrp_count', 'feildName': '重叠覆盖采样点', 'datatype': 'character varying', 'columntype': '1',
     'feildtype': '5GMR覆盖-小区天', 'table': 'appdbv3.a_common_mro_scssrsrp_nr_nrcell', 'tableName': '5GMR覆盖-小区天'},
    {'feild': 'mro_all_phr_count', 'feildName': 'PHR总采样点', 'datatype': 'character varying', 'columntype': '1',
     'feildtype': '5GMR覆盖-小区天', 'table': 'appdbv3.a_common_mro_scssrsrp_nr_nrcell', 'tableName': '5GMR覆盖-小区天'},
    {'feild': 'mro_phr_lt_0', 'feildName': 'PHR小于0采样点数', 'datatype': 'character varying', 'columntype': '1',
     'feildtype': '5GMR覆盖-小区天', 'table': 'appdbv3.a_common_mro_scssrsrp_nr_nrcell', 'tableName': '5GMR覆盖-小区天'},
    {'feild': 'mro_phr_lt_0_rate', 'feildName': 'PHR小于0采样点占比', 'datatype': 'character varying', 'columntype': '1',
     'feildtype': '5GMR覆盖-小区天', 'table': 'appdbv3.a_common_mro_scssrsrp_nr_nrcell', 'tableName': '5GMR覆盖-小区天'},
    {'feild': 'mro_yd_ta_dist_avg', 'feildName': '移动平均TA(M)', 'datatype': 'character varying', 'columntype': '1',
     'feildtype': '5GMR覆盖-小区天', 'table': 'appdbv3.a_common_mro_scssrsrp_nr_nrcell', 'tableName': '5GMR覆盖-小区天'},
]

# ==================== 4G MR覆盖报表字段 ====================
# 基于HAR抓包获取的真实字段配置
MR_4G_FIELDS = [
    {'feild': 'starttime', 'feildName': '开始时间', 'datatype': 'character varying', 'columntype': '1',
     'feildtype': '4G_MRO_RSRP基础性能_小区', 'table': 'appdbv3.a_common_mro_rsrp_lte_cell', 'tableName': '4G_MRO_RSRP基础性能_小区'},
    {'feild': 'cgi', 'feildName': 'cgi', 'datatype': 'character varying', 'columntype': '1',
     'feildtype': '4G_MRO_RSRP基础性能_小区', 'table': 'appdbv3.a_common_mro_rsrp_lte_cell', 'tableName': '4G_MRO_RSRP基础性能_小区'},
    {'feild': 'cell_name', 'feildName': '小区名', 'datatype': 'character varying', 'columntype': '1',
     'feildtype': '4G_MRO_RSRP基础性能_小区', 'table': 'appdbv3.a_common_mro_rsrp_lte_cell', 'tableName': '4G_MRO_RSRP基础性能_小区'},
    {'feild': 'city', 'feildName': '地市', 'datatype': 'character varying', 'columntype': '1',
     'feildtype': '4G_MRO_RSRP基础性能_小区', 'table': 'appdbv3.a_common_mro_rsrp_lte_cell', 'tableName': '4G_MRO_RSRP基础性能_小区'},
    {'feild': 'mro_all_rsrp_count', 'feildName': 'MRO移动总采样点', 'datatype': 'character varying', 'columntype': '1',
     'feildtype': '4G_MRO_RSRP基础性能_小区', 'table': 'appdbv3.a_common_mro_rsrp_lte_cell', 'tableName': '4G_MRO_RSRP基础性能_小区'},
    {'feild': 'mro_yd_rsrp_gt_f110', 'feildName': 'MRO移动大于等于负110DBM的采样点数', 'datatype': 'character varying', 'columntype': '1',
     'feildtype': '4G_MRO_RSRP基础性能_小区', 'table': 'appdbv3.a_common_mro_rsrp_lte_cell', 'tableName': '4G_MRO_RSRP基础性能_小区'},
    {'feild': 'mro_yd_rsrp_rate', 'feildName': 'MRO移动覆盖率', 'datatype': 'character varying', 'columntype': '1',
     'feildtype': '4G_MRO_RSRP基础性能_小区', 'table': 'appdbv3.a_common_mro_rsrp_lte_cell', 'tableName': '4G_MRO_RSRP基础性能_小区'},
    {'feild': 'mro_overlap_rsrp_rate', 'feildName': 'MRO移动重叠覆盖率', 'datatype': 'character varying', 'columntype': '1',
     'feildtype': '4G_MRO_RSRP基础性能_小区', 'table': 'appdbv3.a_common_mro_rsrp_lte_cell', 'tableName': '4G_MRO_RSRP基础性能_小区'},
    {'feild': 'mro_overlap_rsrp_count', 'feildName': 'MRO移动覆盖采样点数', 'datatype': 'character varying', 'columntype': '1',
     'feildtype': '4G_MRO_RSRP基础性能_小区', 'table': 'appdbv3.a_common_mro_rsrp_lte_cell', 'tableName': '4G_MRO_RSRP基础性能_小区'},
    {'feild': 'rsrp110_dist_avg', 'feildName': '平均TA', 'datatype': 'character varying', 'columntype': '1',
     'feildtype': '4G_MRO_RSRP基础性能_小区', 'table': 'appdbv3.a_common_mro_rsrp_lte_cell', 'tableName': '4G_MRO_RSRP基础性能_小区'},
]

# ==================== VoLTE小区监控预警字段 ====================
VOLTE_WARNING_FIELDS = [
    {'feild': 'starttime', 'feildName': '时间', 'datatype': 'timestamp', 'columntype': '1',
     'feildtype': 'VoLTE小区监控预警数据表-天', 'table': 'csem.f_nk_volte_keykpi_cell_d', 'tableName': 'VoLTE小区监控预警数据表-天'},
    {'feild': 'city', 'feildName': '地市', 'datatype': 'character varying', 'columntype': '1',
     'feildtype': 'VoLTE小区监控预警数据表-天', 'table': 'csem.f_nk_volte_keykpi_cell_d', 'tableName': 'VoLTE小区监控预警数据表-天'},
    {'feild': 'cgi', 'feildName': '小区', 'datatype': 'character varying', 'columntype': '1',
     'feildtype': 'VoLTE小区监控预警数据表-天', 'table': 'csem.f_nk_volte_keykpi_cell_d', 'tableName': 'VoLTE小区监控预警数据表-天'},
    {'feild': 'grid', 'feildName': '责任网格', 'datatype': 'character varying', 'columntype': '1',
     'feildtype': 'VoLTE小区监控预警数据表-天', 'table': 'csem.f_nk_volte_keykpi_cell_d', 'tableName': 'VoLTE小区监控预警数据表-天'},
    {'feild': 'area', 'feildName': '区县', 'datatype': 'character varying', 'columntype': '1',
     'feildtype': 'VoLTE小区监控预警数据表-天', 'table': 'csem.f_nk_volte_keykpi_cell_d', 'tableName': 'VoLTE小区监控预警数据表-天'},
    {'feild': 'nrcell_name', 'feildName': '小区名称', 'datatype': 'character varying', 'columntype': '1',
     'feildtype': 'VoLTE小区监控预警数据表-天', 'table': 'csem.f_nk_volte_keykpi_cell_d', 'tableName': 'VoLTE小区监控预警数据表-天'},
    {'feild': 'cs_reg1_suss_rate', 'feildName': '初始注册成功率（控制面）', 'datatype': 'numeric', 'columntype': '1',
     'feildtype': 'VoLTE小区监控预警数据表-天', 'table': 'csem.f_nk_volte_keykpi_cell_d', 'tableName': 'VoLTE小区监控预警数据表-天'},
    {'feild': 'cs_reg_suss_rate', 'feildName': 'VoLTE注册成功率（控制面）', 'datatype': 'numeric', 'columntype': '1',
     'feildtype': 'VoLTE小区监控预警数据表-天', 'table': 'csem.f_nk_volte_keykpi_cell_d', 'tableName': 'VoLTE小区监控预警数据表-天'},
    {'feild': 'cs_sbc_suss_rate', 'feildName': '呼叫接通率(MOC+MTC)（控制面）', 'datatype': 'numeric', 'columntype': '1',
     'feildtype': 'VoLTE小区监控预警数据表-天', 'table': 'csem.f_nk_volte_keykpi_cell_d', 'tableName': 'VoLTE小区监控预警数据表-天'},
    {'feild': 'cs_sbc_drops_rate', 'feildName': 'VOLTE+掉话率（控制面）', 'datatype': 'numeric', 'columntype': '1',
     'feildtype': 'VoLTE小区监控预警数据表-天', 'table': 'csem.f_nk_volte_keykpi_cell_d', 'tableName': 'VoLTE小区监控预警数据表-天'},
    {'feild': 'mconv_rtp_ul_mos_avg', 'feildName': 'RTP上行平均MOS（会话）', 'datatype': 'numeric', 'columntype': '1',
     'feildtype': 'VoLTE小区监控预警数据表-天', 'table': 'csem.f_nk_volte_keykpi_cell_d', 'tableName': 'VoLTE小区监控预警数据表-天'},
    {'feild': 'mconv_rtp_dl_mos_avg', 'feildName': 'RTP下行平均MOS（会话）', 'datatype': 'numeric', 'columntype': '1',
     'feildtype': 'VoLTE小区监控预警数据表-天', 'table': 'csem.f_nk_volte_keykpi_cell_d', 'tableName': 'VoLTE小区监控预警数据表-天'},
    {'feild': 'mconv_rtp_ul_pkts_lost_rate', 'feildName': 'RTP上行丢包率（会话）', 'datatype': 'numeric', 'columntype': '1',
     'feildtype': 'VoLTE小区监控预警数据表-天', 'table': 'csem.f_nk_volte_keykpi_cell_d', 'tableName': 'VoLTE小区监控预警数据表-天'},
    {'feild': 'mconv_rtp_dl_pkts_lost_rate', 'feildName': 'RTP下行丢包率（会话）', 'datatype': 'numeric', 'columntype': '1',
     'feildtype': 'VoLTE小区监控预警数据表-天', 'table': 'csem.f_nk_volte_keykpi_cell_d', 'tableName': 'VoLTE小区监控预警数据表-天'},
    {'feild': 'msli_ul_tunzi_len_rate', 'feildName': 'VoLTE语音上行质差率（片段）', 'datatype': 'numeric', 'columntype': '1',
     'feildtype': 'VoLTE小区监控预警数据表-天', 'table': 'csem.f_nk_volte_keykpi_cell_d', 'tableName': 'VoLTE小区监控预警数据表-天'},
    {'feild': 'msli_dl_tunzi_len_rate', 'feildName': 'VoLTE语音下行质差率（片段）', 'datatype': 'numeric', 'columntype': '1',
     'feildtype': 'VoLTE小区监控预警数据表-天', 'table': 'csem.f_nk_volte_keykpi_cell_d', 'tableName': 'VoLTE小区监控预警数据表-天'},
    {'feild': 'volte_sbc_net_suss', 'feildName': 'VoLTE_网络接通次数(MOC+MTC)', 'datatype': 'numeric', 'columntype': '1',
     'feildtype': 'VoLTE小区监控预警数据表-天', 'table': 'csem.f_nk_volte_keykpi_cell_d', 'tableName': 'VoLTE小区监控预警数据表-天'},
    {'feild': 'volte_sbc_drops', 'feildName': 'VoLTE_掉话次数', 'datatype': 'numeric', 'columntype': '1',
     'feildtype': 'VoLTE小区监控预警数据表-天', 'table': 'csem.f_nk_volte_keykpi_cell_d', 'tableName': 'VoLTE小区监控预警数据表-天'},
    {'feild': 'volte_ul_tunzi_len', 'feildName': 'VoLTE_语音上行质差时长(s)', 'datatype': 'numeric', 'columntype': '1',
     'feildtype': 'VoLTE小区监控预警数据表-天', 'table': 'csem.f_nk_volte_keykpi_cell_d', 'tableName': 'VoLTE小区监控预警数据表-天'},
    {'feild': 'volte_dl_tunzi_len', 'feildName': 'VoLTE_语音下行质差时长(s)', 'datatype': 'numeric', 'columntype': '1',
     'feildtype': 'VoLTE小区监控预警数据表-天', 'table': 'csem.f_nk_volte_keykpi_cell_d', 'tableName': 'VoLTE小区监控预警数据表-天'},
]

# ==================== VONR小区监控预警字段 ====================
VONR_WARNING_FIELDS = [
    {'feild': 'starttime', 'feildName': '时间', 'datatype': 'timestamp', 'columntype': '1',
     'feildtype': 'VONR小区监控预警数据表-天', 'table': 'csem.f_nk_vonr_keykpi_cell_d', 'tableName': 'VONR小区监控预警数据表-天'},
    {'feild': 'city', 'feildName': '地市', 'datatype': 'character varying', 'columntype': '1',
     'feildtype': 'VONR小区监控预警数据表-天', 'table': 'csem.f_nk_vonr_keykpi_cell_d', 'tableName': 'VONR小区监控预警数据表-天'},
    {'feild': 'cgi', 'feildName': '小区', 'datatype': 'character varying', 'columntype': '1',
     'feildtype': 'VONR小区监控预警数据表-天', 'table': 'csem.f_nk_vonr_keykpi_cell_d', 'tableName': 'VONR小区监控预警数据表-天'},
    {'feild': 'grid', 'feildName': '责任网格', 'datatype': 'character varying', 'columntype': '1',
     'feildtype': 'VONR小区监控预警数据表-天', 'table': 'csem.f_nk_vonr_keykpi_cell_d', 'tableName': 'VONR小区监控预警数据表-天'},
    {'feild': 'area', 'feildName': '区县', 'datatype': 'character varying', 'columntype': '1',
     'feildtype': 'VONR小区监控预警数据表-天', 'table': 'csem.f_nk_vonr_keykpi_cell_d', 'tableName': 'VONR小区监控预警数据表-天'},
    {'feild': 'nrcell_name', 'feildName': '小区名称', 'datatype': 'character varying', 'columntype': '1',
     'feildtype': 'VONR小区监控预警数据表-天', 'table': 'csem.f_nk_vonr_keykpi_cell_d', 'tableName': 'VONR小区监控预警数据表-天'},
    {'feild': 'sacs_start_vonr_call_net_succ_rate', 'feildName': 'VoNR呼叫网络接通率（SA控制起始）', 'datatype': 'numeric', 'columntype': '1',
     'feildtype': 'VONR小区监控预警数据表-天', 'table': 'csem.f_nk_vonr_keykpi_cell_d', 'tableName': 'VONR小区监控预警数据表-天'},
    {'feild': 'sacs_start_vonr_call_drop_rate', 'feildName': 'VoNR掉话率（SA控制起始）', 'datatype': 'numeric', 'columntype': '1',
     'feildtype': 'VONR小区监控预警数据表-天', 'table': 'csem.f_nk_vonr_keykpi_cell_d', 'tableName': 'VONR小区监控预警数据表-天'},
    {'feild': 'mconv_rtp_ul_mos_avg', 'feildName': 'RTP上行平均MOS', 'datatype': 'numeric', 'columntype': '1',
     'feildtype': 'VONR小区监控预警数据表-天', 'table': 'csem.f_nk_vonr_keykpi_cell_d', 'tableName': 'VONR小区监控预警数据表-天'},
    {'feild': 'mconv_rtp_dl_mos_avg', 'feildName': 'RTP下行平均MOS', 'datatype': 'numeric', 'columntype': '1',
     'feildtype': 'VONR小区监控预警数据表-天', 'table': 'csem.f_nk_vonr_keykpi_cell_d', 'tableName': 'VONR小区监控预警数据表-天'},
    {'feild': 'mconv_rtp_ul_pkts_lost_rate', 'feildName': 'RTP上行丢包率', 'datatype': 'numeric', 'columntype': '1',
     'feildtype': 'VONR小区监控预警数据表-天', 'table': 'csem.f_nk_vonr_keykpi_cell_d', 'tableName': 'VONR小区监控预警数据表-天'},
    {'feild': 'mconv_rtp_dl_pkts_lost_rate', 'feildName': 'RTP下行丢包率', 'datatype': 'numeric', 'columntype': '1',
     'feildtype': 'VONR小区监控预警数据表-天', 'table': 'csem.f_nk_vonr_keykpi_cell_d', 'tableName': 'VONR小区监控预警数据表-天'},
    {'feild': 'msli_ul_tunzi_len_rate', 'feildName': 'VoNR语音上行质差率', 'datatype': 'numeric', 'columntype': '1',
     'feildtype': 'VONR小区监控预警数据表-天', 'table': 'csem.f_nk_vonr_keykpi_cell_d', 'tableName': 'VONR小区监控预警数据表-天'},
    {'feild': 'msli_dl_tunzi_len_rate', 'feildName': 'VoNR语音下行质差率', 'datatype': 'numeric', 'columntype': '1',
     'feildtype': 'VONR小区监控预警数据表-天', 'table': 'csem.f_nk_vonr_keykpi_cell_d', 'tableName': 'VONR小区监控预警数据表-天'},
]

# ==================== EPSFB小区监控预警字段 ====================
EPSFB_WARNING_FIELDS = [
    {'feild': 'starttime', 'feildName': '时间', 'datatype': 'timestamp', 'columntype': '1',
     'feildtype': 'EPSFB小区监控预警数据表-天', 'table': 'csem.f_nk_epsfb_keykpi_cell_d', 'tableName': 'EPSFB小区监控预警数据表-天'},
    {'feild': 'city', 'feildName': '地市', 'datatype': 'character varying', 'columntype': '1',
     'feildtype': 'EPSFB小区监控预警数据表-天', 'table': 'csem.f_nk_epsfb_keykpi_cell_d', 'tableName': 'EPSFB小区监控预警数据表-天'},
    {'feild': 'cgi', 'feildName': '小区', 'datatype': 'character varying', 'columntype': '1',
     'feildtype': 'EPSFB小区监控预警数据表-天', 'table': 'csem.f_nk_epsfb_keykpi_cell_d', 'tableName': 'EPSFB小区监控预警数据表-天'},
    {'feild': 'grid', 'feildName': '责任网格', 'datatype': 'character varying', 'columntype': '1',
     'feildtype': 'EPSFB小区监控预警数据表-天', 'table': 'csem.f_nk_epsfb_keykpi_cell_d', 'tableName': 'EPSFB小区监控预警数据表-天'},
    {'feild': 'area', 'feildName': '区县', 'datatype': 'character varying', 'columntype': '1',
     'feildtype': 'EPSFB小区监控预警数据表-天', 'table': 'csem.f_nk_epsfb_keykpi_cell_d', 'tableName': 'EPSFB小区监控预警数据表-天'},
    {'feild': 'nrcell_name', 'feildName': '小区名称', 'datatype': 'character varying', 'columntype': '1',
     'feildtype': 'EPSFB小区监控预警数据表-天', 'table': 'csem.f_nk_epsfb_keykpi_cell_d', 'tableName': 'EPSFB小区监控预警数据表-天'},
    {'feild': 'sacs_start_call_net_succ_rate', 'feildName': 'EPSFB呼叫网络接通率（SA控制起始）', 'datatype': 'numeric', 'columntype': '1',
     'feildtype': 'EPSFB小区监控预警数据表-天', 'table': 'csem.f_nk_epsfb_keykpi_cell_d', 'tableName': 'EPSFB小区监控预警数据表-天'},
    {'feild': 'sacs_start_call_drop_rate', 'feildName': 'EPSFB掉话率（SA控制起始）', 'datatype': 'numeric', 'columntype': '1',
     'feildtype': 'EPSFB小区监控预警数据表-天', 'table': 'csem.f_nk_epsfb_keykpi_cell_d', 'tableName': 'EPSFB小区监控预警数据表-天'},
    {'feild': 'sacs_start_fb_succ_rate', 'feildName': 'EPSFB切换成功率（SA控制起始）', 'datatype': 'numeric', 'columntype': '1',
     'feildtype': 'EPSFB小区监控预警数据表-天', 'table': 'csem.f_nk_epsfb_keykpi_cell_d', 'tableName': 'EPSFB小区监控预警数据表-天'},
    {'feild': 'mconv_rtp_ul_mos_avg', 'feildName': 'RTP上行平均MOS', 'datatype': 'numeric', 'columntype': '1',
     'feildtype': 'EPSFB小区监控预警数据表-天', 'table': 'csem.f_nk_epsfb_keykpi_cell_d', 'tableName': 'EPSFB小区监控预警数据表-天'},
    {'feild': 'mconv_rtp_dl_mos_avg', 'feildName': 'RTP下行平均MOS', 'datatype': 'numeric', 'columntype': '1',
     'feildtype': 'EPSFB小区监控预警数据表-天', 'table': 'csem.f_nk_epsfb_keykpi_cell_d', 'tableName': 'EPSFB小区监控预警数据表-天'},
    {'feild': 'mconv_rtp_ul_pkts_lost_rate', 'feildName': 'RTP上行丢包率', 'datatype': 'numeric', 'columntype': '1',
     'feildtype': 'EPSFB小区监控预警数据表-天', 'table': 'csem.f_nk_epsfb_keykpi_cell_d', 'tableName': 'EPSFB小区监控预警数据表-天'},
    {'feild': 'mconv_rtp_dl_pkts_lost_rate', 'feildName': 'RTP下行丢包率', 'datatype': 'numeric', 'columntype': '1',
     'feildtype': 'EPSFB小区监控预警数据表-天', 'table': 'csem.f_nk_epsfb_keykpi_cell_d', 'tableName': 'EPSFB小区监控预警数据表-天'},
]

# ==================== 4G小区性能KPI报表字段（全程完好率） ====================
KPI_4G_FIELDS = [
    {'feild': 'starttime', 'feildName': '开始时间', 'datatype': 'character varying', 'columntype': '2',
     'feildtype': '公共_4G小区性能KPI报表_小区', 'table': 'appdbv3.a_common_pm_lte', 'tableName': '公共_4G小区性能KPI报表_小区'},
    {'feild': 'cgi', 'feildName': 'CGI', 'datatype': 'character varying', 'columntype': '1',
     'feildtype': '公共_4G小区性能KPI报表_小区', 'table': 'appdbv3.a_common_pm_lte', 'tableName': '公共_4G小区性能KPI报表_小区'},
    {'feild': 'cell_name', 'feildName': '小区名称', 'datatype': 'character varying', 'columntype': '1',
     'feildtype': '公共_4G小区性能KPI报表_小区', 'table': 'appdbv3.a_common_pm_lte', 'tableName': '公共_4G小区性能KPI报表_小区'},
    {'feild': 'city', 'feildName': '所属地市', 'datatype': 'character varying', 'columntype': '1',
     'feildtype': '公共_4G小区性能KPI报表_小区', 'table': 'appdbv3.a_common_pm_lte', 'tableName': '公共_4G小区性能KPI报表_小区'},
    {'feild': 'attconnestab', 'feildName': 'RRC连接建立请求次数', 'datatype': 'bigint', 'columntype': '1',
     'feildtype': '公共_4G小区性能KPI报表_小区', 'table': 'appdbv3.a_common_pm_lte', 'tableName': '公共_4G小区性能KPI报表_小区'},
    {'feild': 'nbrsuccestab', 'feildName': 'E-RAB建立成功数', 'datatype': 'bigint', 'columntype': '1',
     'feildtype': '公共_4G小区性能KPI报表_小区', 'table': 'appdbv3.a_common_pm_lte', 'tableName': '公共_4G小区性能KPI报表_小区'},
    {'feild': 'nbrattestab', 'feildName': 'E-RAB建立请求数', 'datatype': 'bigint', 'columntype': '1',
     'feildtype': '公共_4G小区性能KPI报表_小区', 'table': 'appdbv3.a_common_pm_lte', 'tableName': '公共_4G小区性能KPI报表_小区'},
    {'feild': 'nbrleft', 'feildName': '遗留上下文个数', 'datatype': 'bigint', 'columntype': '1',
     'feildtype': '公共_4G小区性能KPI报表_小区', 'table': 'appdbv3.a_common_pm_lte', 'tableName': '公共_4G小区性能KPI报表_小区'},
    {'feild': 'nbrhoinc', 'feildName': '切换入E-RAB数', 'datatype': 'bigint', 'columntype': '1',
     'feildtype': '公共_4G小区性能KPI报表_小区', 'table': 'appdbv3.a_common_pm_lte', 'tableName': '公共_4G小区性能KPI报表_小区'},
    {'feild': 'hofail', 'feildName': '切出失败的E-RAB数', 'datatype': 'bigint', 'columntype': '1',
     'feildtype': '公共_4G小区性能KPI报表_小区', 'table': 'appdbv3.a_common_pm_lte', 'tableName': '公共_4G小区性能KPI报表_小区'},
    {'feild': 'nbrreqrelenb_normal', 'feildName': '正常的eNB请求释放的E-RAB数', 'datatype': 'bigint', 'columntype': '1',
     'feildtype': '公共_4G小区性能KPI报表_小区', 'table': 'appdbv3.a_common_pm_lte', 'tableName': '公共_4G小区性能KPI报表_小区'},
    {'feild': 'nbrreqrelenb', 'feildName': 'eNB请求释放的E-RAB数', 'datatype': 'bigint', 'columntype': '1',
     'feildtype': '公共_4G小区性能KPI报表_小区', 'table': 'appdbv3.a_common_pm_lte', 'tableName': '公共_4G小区性能KPI报表_小区'},
    {'feild': 'ho_succ_out', 'feildName': '切换成功次数', 'datatype': 'bigint', 'columntype': '1',
     'feildtype': '公共_4G小区性能KPI报表_小区', 'table': 'appdbv3.a_common_pm_lte', 'tableName': '公共_4G小区性能KPI报表_小区'},
    {'feild': 'ho_att__out', 'feildName': '切换请求次数', 'datatype': 'bigint', 'columntype': '1',
     'feildtype': '公共_4G小区性能KPI报表_小区', 'table': 'appdbv3.a_common_pm_lte', 'tableName': '公共_4G小区性能KPI报表_小区'},
    {'feild': 'state', 'feildName': '网元状态', 'datatype': 'character varying', 'columntype': '1',
     'feildtype': '公共_4G小区性能KPI报表_小区', 'table': 'appdbv3.a_common_pm_lte', 'tableName': '公共_4G小区性能KPI报表_小区'},
    {'feild': 'network_type', 'feildName': '网络制式', 'datatype': 'character varying', 'columntype': '1',
     'feildtype': '公共_4G小区性能KPI报表_小区', 'table': 'appdbv3.a_common_pm_lte', 'tableName': '公共_4G小区性能KPI报表_小区'},
    {'feild': 'cover_type', 'feildName': '覆盖类型', 'datatype': 'character varying', 'columntype': '1',
     'feildtype': '公共_4G小区性能KPI报表_小区', 'table': 'appdbv3.a_common_pm_lte', 'tableName': '公共_4G小区性能KPI报表_小区'},
    {'feild': 'vendor', 'feildName': '厂家', 'datatype': 'character varying', 'columntype': '1',
     'feildtype': '公共_4G小区性能KPI报表_小区', 'table': 'appdbv3.a_common_pm_lte', 'tableName': '公共_4G小区性能KPI报表_小区'},
    {'feild': 'branch', 'feildName': '人力区县分公司', 'datatype': 'character varying', 'columntype': '1',
     'feildtype': '公共_4G小区性能KPI报表_小区', 'table': 'appdbv3.a_common_pm_lte', 'tableName': '公共_4G小区性能KPI报表_小区'},
    {'feild': 'grid', 'feildName': '网格', 'datatype': 'character varying', 'columntype': '1',
     'feildtype': '公共_4G小区性能KPI报表_小区', 'table': 'appdbv3.a_common_pm_lte', 'tableName': '公共_4G小区性能KPI报表_小区'},
]

# ==================== 5G小区性能KPI报表字段（全程完好率） ====================
KPI_5G_FIELDS = [
    {'feild': 'starttime', 'feildName': '数据时间', 'datatype': 'character varying', 'columntype': '1',
     'feildtype': '公共_5G小区性能KPI报表_小区', 'table': 'appdbv3.a_common_pm_sacu', 'tableName': '公共_5G小区性能KPI报表_小区'},
    {'feild': 'ncgi', 'feildName': 'NCGI', 'datatype': 'character varying', 'columntype': '1',
     'feildtype': '公共_5G小区性能KPI报表_小区', 'table': 'appdbv3.a_common_pm_sacu', 'tableName': '公共_5G小区性能KPI报表_小区'},
    {'feild': 'nrcell_name', 'feildName': '小区名称', 'datatype': 'character varying', 'columntype': '1',
     'feildtype': '公共_5G小区性能KPI报表_小区', 'table': 'appdbv3.a_common_pm_sacu', 'tableName': '公共_5G小区性能KPI报表_小区'},
    {'feild': 'city', 'feildName': '所属地市', 'datatype': 'character varying', 'columntype': '1',
     'feildtype': '公共_5G小区性能KPI报表_小区', 'table': 'appdbv3.a_common_pm_sacu', 'tableName': '公共_5G小区性能KPI报表_小区'},
    {'feild': 'rrc_attconnestab', 'feildName': 'RRC连接建立请求次数', 'datatype': 'bigint', 'columntype': '1',
     'feildtype': '公共_5G小区性能KPI报表_小区', 'table': 'appdbv3.a_common_pm_sacu', 'tableName': '公共_5G小区性能KPI报表_小区'},
    {'feild': 'rrc_succconnestab', 'feildName': 'RRC连接建立成功次数', 'datatype': 'bigint', 'columntype': '1',
     'feildtype': '公共_5G小区性能KPI报表_小区', 'table': 'appdbv3.a_common_pm_sacu', 'tableName': '公共_5G小区性能KPI报表_小区'},
    {'feild': 'flow_nbrattestab', 'feildName': 'Flow建立请求数', 'datatype': 'bigint', 'columntype': '1',
     'feildtype': '公共_5G小区性能KPI报表_小区', 'table': 'appdbv3.a_common_pm_sacu', 'tableName': '公共_5G小区性能KPI报表_小区'},
    {'feild': 'flow_nbrsuccestab', 'feildName': 'Flow建立成功数', 'datatype': 'bigint', 'columntype': '1',
     'feildtype': '公共_5G小区性能KPI报表_小区', 'table': 'appdbv3.a_common_pm_sacu', 'tableName': '公共_5G小区性能KPI报表_小区'},
    {'feild': 'ngsig_connestabatt', 'feildName': 'NG接口UE相关逻辑信令连接建立请求次数', 'datatype': 'bigint', 'columntype': '1',
     'feildtype': '公共_5G小区性能KPI报表_小区', 'table': 'appdbv3.a_common_pm_sacu', 'tableName': '公共_5G小区性能KPI报表_小区'},
    {'feild': 'ngsig_connestabsucc', 'feildName': 'NG接口UE相关逻辑信令连接建立成功次数', 'datatype': 'bigint', 'columntype': '1',
     'feildtype': '公共_5G小区性能KPI报表_小区', 'table': 'appdbv3.a_common_pm_sacu', 'tableName': '公共_5G小区性能KPI报表_小区'},
    {'feild': 'context_attrelgnb', 'feildName': 'gNB请求释放上下文数', 'datatype': 'bigint', 'columntype': '1',
     'feildtype': '公共_5G小区性能KPI报表_小区', 'table': 'appdbv3.a_common_pm_sacu', 'tableName': '公共_5G小区性能KPI报表_小区'},
    {'feild': 'context_attrelgnb_normal', 'feildName': '正常的gNB请求释放上下文数', 'datatype': 'bigint', 'columntype': '1',
     'feildtype': '公共_5G小区性能KPI报表_小区', 'table': 'appdbv3.a_common_pm_sacu', 'tableName': '公共_5G小区性能KPI报表_小区'},
    {'feild': 'context_succinitalsetup', 'feildName': '初始上下文建立成功次数', 'datatype': 'bigint', 'columntype': '1',
     'feildtype': '公共_5G小区性能KPI报表_小区', 'table': 'appdbv3.a_common_pm_sacu', 'tableName': '公共_5G小区性能KPI报表_小区'},
    {'feild': 'context_nbrleft', 'feildName': '遗留上下文个数', 'datatype': 'bigint', 'columntype': '1',
     'feildtype': '公共_5G小区性能KPI报表_小区', 'table': 'appdbv3.a_common_pm_sacu', 'tableName': '公共_5G小区性能KPI报表_小区'},
    {'feild': 'ho_succexecinc', 'feildName': '切换入成功次数', 'datatype': 'bigint', 'columntype': '1',
     'feildtype': '公共_5G小区性能KPI报表_小区', 'table': 'appdbv3.a_common_pm_sacu', 'tableName': '公共_5G小区性能KPI报表_小区'},
    {'feild': 'rrc_succconnreestab_nonsrccell', 'feildName': 'RRC连接重建成功次数(非源侧小区)', 'datatype': 'bigint', 'columntype': '1',
     'feildtype': '公共_5G小区性能KPI报表_小区', 'table': 'appdbv3.a_common_pm_sacu', 'tableName': '公共_5G小区性能KPI报表_小区'},
    {'feild': 'ho_succoutintercung', 'feildName': 'gNB间NG切换出成功次数', 'datatype': 'bigint', 'columntype': '1',
     'feildtype': '公共_5G小区性能KPI报表_小区', 'table': 'appdbv3.a_common_pm_sacu', 'tableName': '公共_5G小区性能KPI报表_小区'},
    {'feild': 'ho_succoutintercuxn', 'feildName': 'gNB间Xn切换出成功次数', 'datatype': 'bigint', 'columntype': '1',
     'feildtype': '公共_5G小区性能KPI报表_小区', 'table': 'appdbv3.a_common_pm_sacu', 'tableName': '公共_5G小区性能KPI报表_小区'},
    {'feild': 'ho_attoutintercung', 'feildName': 'gNB间NG切换出准备请求次数', 'datatype': 'bigint', 'columntype': '1',
     'feildtype': '公共_5G小区性能KPI报表_小区', 'table': 'appdbv3.a_common_pm_sacu', 'tableName': '公共_5G小区性能KPI报表_小区'},
    {'feild': 'ho_attoutintercuxn', 'feildName': 'gNB间Xn切换出准备请求次数', 'datatype': 'bigint', 'columntype': '1',
     'feildtype': '公共_5G小区性能KPI报表_小区', 'table': 'appdbv3.a_common_pm_sacu', 'tableName': '公共_5G小区性能KPI报表_小区'},
    {'feild': 'ho_succoutintracuinterdu', 'feildName': 'CU内DU间切换出执行成功次数', 'datatype': 'bigint', 'columntype': '1',
     'feildtype': '公共_5G小区性能KPI报表_小区', 'table': 'appdbv3.a_common_pm_sacu', 'tableName': '公共_5G小区性能KPI报表_小区'},
    {'feild': 'ho_attoutintracuinterdu', 'feildName': 'CU内DU间切换出执行请求次数', 'datatype': 'bigint', 'columntype': '1',
     'feildtype': '公共_5G小区性能KPI报表_小区', 'table': 'appdbv3.a_common_pm_sacu', 'tableName': '公共_5G小区性能KPI报表_小区'},
    {'feild': 'ho_succoutintradu', 'feildName': 'CU内DU内切换出成功次数', 'datatype': 'bigint', 'columntype': '1',
     'feildtype': '公共_5G小区性能KPI报表_小区', 'table': 'appdbv3.a_common_pm_sacu', 'tableName': '公共_5G小区性能KPI报表_小区'},
    {'feild': 'ho_attoutcuintradu', 'feildName': 'CU内DU内切换出执行请求次数', 'datatype': 'bigint', 'columntype': '1',
     'feildtype': '公共_5G小区性能KPI报表_小区', 'table': 'appdbv3.a_common_pm_sacu', 'tableName': '公共_5G小区性能KPI报表_小区'},
    {'feild': 'state', 'feildName': '网元状态', 'datatype': 'character varying', 'columntype': '1',
     'feildtype': '公共_5G小区性能KPI报表_小区', 'table': 'appdbv3.a_common_pm_sacu', 'tableName': '公共_5G小区性能KPI报表_小区'},
    {'feild': 'vendor', 'feildName': '设备厂家', 'datatype': 'character varying', 'columntype': '1',
     'feildtype': '公共_5G小区性能KPI报表_小区', 'table': 'appdbv3.a_common_pm_sacu', 'tableName': '公共_5G小区性能KPI报表_小区'},
    {'feild': 'branch', 'feildName': '人力区县分公司', 'datatype': 'character varying', 'columntype': '1',
     'feildtype': '公共_5G小区性能KPI报表_小区', 'table': 'appdbv3.a_common_pm_sacu', 'tableName': '公共_5G小区性能KPI报表_小区'},
    {'feild': 'grid', 'feildName': '责任网格', 'datatype': 'character varying', 'columntype': '1',
     'feildtype': '公共_5G小区性能KPI报表_小区', 'table': 'appdbv3.a_common_pm_sacu', 'tableName': '公共_5G小区性能KPI报表_小区'},
    {'feild': 'area', 'feildName': '所属区县', 'datatype': 'character varying', 'columntype': '1',
     'feildtype': '公共_5G小区性能KPI报表_小区', 'table': 'appdbv3.a_common_pm_sacu', 'tableName': '公共_5G小区性能KPI报表_小区'},
]

# ==================== 5G语音小区字段 ====================
VOICE_5G_FIELDS = [
    {'feild': 'starttime', 'feildName': '时间', 'datatype': 'timestamp', 'columntype': '1',
     'feildtype': 'VONR小区监控预警数据表-天', 'table': 'csem.f_nk_vonr_keykpi_cell_d', 'tableName': 'VONR小区监控预警数据表-天'},
    {'feild': 'city', 'feildName': '地市', 'datatype': 'character varying', 'columntype': '1',
     'feildtype': 'VONR小区监控预警数据表-天', 'table': 'csem.f_nk_vonr_keykpi_cell_d', 'tableName': 'VONR小区监控预警数据表-天'},
    {'feild': 'cgi', 'feildName': '小区', 'datatype': 'character varying', 'columntype': '1',
     'feildtype': 'VONR小区监控预警数据表-天', 'table': 'csem.f_nk_vonr_keykpi_cell_d', 'tableName': 'VONR小区监控预警数据表-天'},
    {'feild': 'grid', 'feildName': '责任网格', 'datatype': 'character varying', 'columntype': '1',
     'feildtype': 'VONR小区监控预警数据表-天', 'table': 'csem.f_nk_vonr_keykpi_cell_d', 'tableName': 'VONR小区监控预警数据表-天'},
    {'feild': 'area', 'feildName': '区县', 'datatype': 'character varying', 'columntype': '1',
     'feildtype': 'VONR小区监控预警数据表-天', 'table': 'csem.f_nk_vonr_keykpi_cell_d', 'tableName': 'VONR小区监控预警数据表-天'},
    {'feild': 'nrcell_name', 'feildName': '小区名称', 'datatype': 'character varying', 'columntype': '1',
     'feildtype': 'VONR小区监控预警数据表-天', 'table': 'csem.f_nk_vonr_keykpi_cell_d', 'tableName': 'VONR小区监控预警数据表-天'},
    {'feild': 'vonr_ul_tunzi_len', 'feildName': 'VoNR语音上行质差时长(s)', 'datatype': 'numeric', 'columntype': '1',
     'feildtype': 'VONR小区监控预警数据表-天', 'table': 'csem.f_nk_vonr_keykpi_cell_d', 'tableName': 'VONR小区监控预警数据表-天'},
    {'feild': 'vonr_ul_dantong_len', 'feildName': 'VoNR语音上行单通时长(s)', 'datatype': 'numeric', 'columntype': '1',
     'feildtype': 'VONR小区监控预警数据表-天', 'table': 'csem.f_nk_vonr_keykpi_cell_d', 'tableName': 'VONR小区监控预警数据表-天'},
    {'feild': 'vonr_ul_duanxu_len', 'feildName': 'VoNR语音上行断续时长(s)', 'datatype': 'numeric', 'columntype': '1',
     'feildtype': 'VONR小区监控预警数据表-天', 'table': 'csem.f_nk_vonr_keykpi_cell_d', 'tableName': 'VONR小区监控预警数据表-天'},
    {'feild': 'vonr_ul_voice_sum_len', 'feildName': 'VoNR语音上行总时长(s)', 'datatype': 'numeric', 'columntype': '1',
     'feildtype': 'VONR小区监控预警数据表-天', 'table': 'csem.f_nk_vonr_keykpi_cell_d', 'tableName': 'VONR小区监控预警数据表-天'},
    {'feild': 'vonr_ans_voice_call', 'feildName': 'VoNR语音通话总次数', 'datatype': 'numeric', 'columntype': '1',
     'feildtype': 'VONR小区监控预警数据表-天', 'table': 'csem.f_nk_vonr_keykpi_cell_d', 'tableName': 'VONR小区监控预警数据表-天'},
    {'feild': 'vonr_dl_tunzi_len', 'feildName': 'VoNR语音下行质差时长(s)', 'datatype': 'numeric', 'columntype': '1',
     'feildtype': 'VONR小区监控预警数据表-天', 'table': 'csem.f_nk_vonr_keykpi_cell_d', 'tableName': 'VONR小区监控预警数据表-天'},
    {'feild': 'vonr_dl_dantong_len', 'feildName': 'VoNR语音下行单通时长(s)', 'datatype': 'numeric', 'columntype': '1',
     'feildtype': 'VONR小区监控预警数据表-天', 'table': 'csem.f_nk_vonr_keykpi_cell_d', 'tableName': 'VONR小区监控预警数据表-天'},
    {'feild': 'vonr_dl_duanxu_len', 'feildName': 'VoNR语音下行断续时长(s)', 'datatype': 'numeric', 'columntype': '1',
     'feildtype': 'VONR小区监控预警数据表-天', 'table': 'csem.f_nk_vonr_keykpi_cell_d', 'tableName': 'VONR小区监控预警数据表-天'},
    {'feild': 'vonr_dl_voice_sum_len', 'feildName': 'VoNR语音下行总时长(s)', 'datatype': 'numeric', 'columntype': '1',
     'feildtype': 'VONR小区监控预警数据表-天', 'table': 'csem.f_nk_vonr_keykpi_cell_d', 'tableName': 'VONR小区监控预警数据表-天'},
]

# ==================== 45G流量与热点评估物理站级字段配置 ====================
FLOW_HOT_SPOT_STATION_FIELDS = [
    {'feild': 'starttime', 'feildName': '开始时间', 'datatype': 'character varying', 'columntype': '1',
     'feildtype': '45G流量与热点评估物理站级', 'table': 'appdbv3.a_cap_ltenr_station', 'tableName': '45G流量与热点评估物理站级'},
    {'feild': 'endtime', 'feildName': '结束时间', 'datatype': 'character varying', 'columntype': '1',
     'feildtype': '45G流量与热点评估物理站级', 'table': 'appdbv3.a_cap_ltenr_station', 'tableName': '45G流量与热点评估物理站级'},
    {'feild': 'city', 'feildName': '地市', 'datatype': 'character varying', 'columntype': '1',
     'feildtype': '45G流量与热点评估物理站级', 'table': 'appdbv3.a_cap_ltenr_station', 'tableName': '45G流量与热点评估物理站级'},
    {'feild': 'station_name', 'feildName': '物理站名称', 'datatype': 'character varying', 'columntype': '1',
     'feildtype': '45G流量与热点评估物理站级', 'table': 'appdbv3.a_cap_ltenr_station', 'tableName': '45G流量与热点评估物理站级'},
    {'feild': 'station_id', 'feildName': '物理站ID', 'datatype': 'character varying', 'columntype': '1',
     'feildtype': '45G流量与热点评估物理站级', 'table': 'appdbv3.a_cap_ltenr_station', 'tableName': '45G流量与热点评估物理站级'},
    {'feild': 'cover_type', 'feildName': '覆盖类型', 'datatype': 'character varying', 'columntype': '1',
     'feildtype': '45G流量与热点评估物理站级', 'table': 'appdbv3.a_cap_ltenr_station', 'tableName': '45G流量与热点评估物理站级'},
    {'feild': 'gnodeb_count', 'feildName': '5G逻辑站数量', 'datatype': 'character varying', 'columntype': '1',
     'feildtype': '45G流量与热点评估物理站级', 'table': 'appdbv3.a_cap_ltenr_station', 'tableName': '45G流量与热点评估物理站级'},
    {'feild': 'enodeb_count', 'feildName': '4G逻辑站数量', 'datatype': 'character varying', 'columntype': '1',
     'feildtype': '45G流量与热点评估物理站级', 'table': 'appdbv3.a_cap_ltenr_station', 'tableName': '45G流量与热点评估物理站级'},
    {'feild': 'nr_cell_count', 'feildName': '5G小区数量', 'datatype': 'character varying', 'columntype': '1',
     'feildtype': '45G流量与热点评估物理站级', 'table': 'appdbv3.a_cap_ltenr_station', 'tableName': '45G流量与热点评估物理站级'},
    {'feild': 'lte_cell_count', 'feildName': '4G小区数量', 'datatype': 'character varying', 'columntype': '1',
     'feildtype': '45G流量与热点评估物理站级', 'table': 'appdbv3.a_cap_ltenr_station', 'tableName': '45G流量与热点评估物理站级'},
    {'feild': 'lte_e_site_list', 'feildName': 'E频站点名列表', 'datatype': 'character varying', 'columntype': '1',
     'feildtype': '45G流量与热点评估物理站级', 'table': 'appdbv3.a_cap_ltenr_station', 'tableName': '45G流量与热点评估物理站级'},
    {'feild': 'lte_d_site_list', 'feildName': 'D频站点名列表', 'datatype': 'character varying', 'columntype': '1',
     'feildtype': '45G流量与热点评估物理站级', 'table': 'appdbv3.a_cap_ltenr_station', 'tableName': '45G流量与热点评估物理站级'},
    {'feild': 'lte_f_site_list', 'feildName': 'F频站点名列表', 'datatype': 'character varying', 'columntype': '1',
     'feildtype': '45G流量与热点评估物理站级', 'table': 'appdbv3.a_cap_ltenr_station', 'tableName': '45G流量与热点评估物理站级'},
    {'feild': 'lte_fdd1800_site_list', 'feildName': 'FDD1800站点名列表', 'datatype': 'character varying', 'columntype': '1',
     'feildtype': '45G流量与热点评估物理站级', 'table': 'appdbv3.a_cap_ltenr_station', 'tableName': '45G流量与热点评估物理站级'},
    {'feild': 'lte_fdd900_site_list', 'feildName': 'FDD900站点名列表', 'datatype': 'character varying', 'columntype': '1',
     'feildtype': '45G流量与热点评估物理站级', 'table': 'appdbv3.a_cap_ltenr_station', 'tableName': '45G流量与热点评估物理站级'},
    {'feild': 'lte_reverse_site_list', 'feildName': '反向4G站点名列表', 'datatype': 'character varying', 'columntype': '1',
     'feildtype': '45G流量与热点评估物理站级', 'table': 'appdbv3.a_cap_ltenr_station', 'tableName': '45G流量与热点评估物理站级'},
    {'feild': 'other_lte_site_list', 'feildName': '其它4G站点列表', 'datatype': 'character varying', 'columntype': '1',
     'feildtype': '45G流量与热点评估物理站级', 'table': 'appdbv3.a_cap_ltenr_station', 'tableName': '45G流量与热点评估物理站级'},
    {'feild': 'nr_2600_site_list', 'feildName': '2.6G站点名列表', 'datatype': 'character varying', 'columntype': '1',
     'feildtype': '45G流量与热点评估物理站级', 'table': 'appdbv3.a_cap_ltenr_station', 'tableName': '45G流量与热点评估物理站级'},
    {'feild': 'nr_700_site_list', 'feildName': '700M站点名列表', 'datatype': 'character varying', 'columntype': '1',
     'feildtype': '45G流量与热点评估物理站级', 'table': 'appdbv3.a_cap_ltenr_station', 'tableName': '45G流量与热点评估物理站级'},
    {'feild': 'nr_4900_site_list', 'feildName': '4.9G站点名列表', 'datatype': 'character varying', 'columntype': '1',
     'feildtype': '45G流量与热点评估物理站级', 'table': 'appdbv3.a_cap_ltenr_station', 'tableName': '45G流量与热点评估物理站级'},
    {'feild': 'other_nr_site_list', 'feildName': '其它5G站点列表', 'datatype': 'character varying', 'columntype': '1',
     'feildtype': '45G流量与热点评估物理站级', 'table': 'appdbv3.a_cap_ltenr_station', 'tableName': '45G流量与热点评估物理站级'},
    {'feild': 'flow_bh_lte_upoctudl', 'feildName': '流量忙时4G流量', 'datatype': 'character varying', 'columntype': '1',
     'feildtype': '45G流量与热点评估物理站级', 'table': 'appdbv3.a_cap_ltenr_station', 'tableName': '45G流量与热点评估物理站级'},
    {'feild': 'flow_bh_nr_upoctudl', 'feildName': '流量忙时5G流量', 'datatype': 'character varying', 'columntype': '1',
     'feildtype': '45G流量与热点评估物理站级', 'table': 'appdbv3.a_cap_ltenr_station', 'tableName': '45G流量与热点评估物理站级'},
    {'feild': 'flow_bh_total_upoctudl', 'feildName': '流量忙时45G总流量', 'datatype': 'character varying', 'columntype': '1',
     'feildtype': '45G流量与热点评估物理站级', 'table': 'appdbv3.a_cap_ltenr_station', 'tableName': '45G流量与热点评估物理站级'},
    {'feild': 'flow_bh_nr_upoctudl_rate', 'feildName': '流量忙时5G流量占比', 'datatype': 'character varying', 'columntype': '1',
     'feildtype': '45G流量与热点评估物理站级', 'table': 'appdbv3.a_cap_ltenr_station', 'tableName': '45G流量与热点评估物理站级'},
    {'feild': 'flow_bh_lte_connmean', 'feildName': '流量忙时4G RRC连接平均数', 'datatype': 'character varying', 'columntype': '1',
     'feildtype': '45G流量与热点评估物理站级', 'table': 'appdbv3.a_cap_ltenr_station', 'tableName': '45G流量与热点评估物理站级'},
    {'feild': 'flow_bh_lte_connmax', 'feildName': '流量忙时4G RRC连接最大数', 'datatype': 'character varying', 'columntype': '1',
     'feildtype': '45G流量与热点评估物理站级', 'table': 'appdbv3.a_cap_ltenr_station', 'tableName': '45G流量与热点评估物理站级'},
    {'feild': 'flow_bh_nr_connmean', 'feildName': '流量忙时5G RRC连接平均数', 'datatype': 'character varying', 'columntype': '1',
     'feildtype': '45G流量与热点评估物理站级', 'table': 'appdbv3.a_cap_ltenr_station', 'tableName': '45G流量与热点评估物理站级'},
    {'feild': 'flow_bh_nr_connmax', 'feildName': '流量忙时5G RRC连接最大数', 'datatype': 'character varying', 'columntype': '1',
     'feildtype': '45G流量与热点评估物理站级', 'table': 'appdbv3.a_cap_ltenr_station', 'tableName': '45G流量与热点评估物理站级'},
    {'feild': 'flow_bh_lte_use_rate', 'feildName': '流量忙时4G利用率', 'datatype': 'character varying', 'columntype': '1',
     'feildtype': '45G流量与热点评估物理站级', 'table': 'appdbv3.a_cap_ltenr_station', 'tableName': '45G流量与热点评估物理站级'},
    {'feild': 'lte_hot_level', 'feildName': '流量忙时4G热点等级', 'datatype': 'character varying', 'columntype': '1',
     'feildtype': '45G流量与热点评估物理站级', 'table': 'appdbv3.a_cap_ltenr_station', 'tableName': '45G流量与热点评估物理站级'},
    {'feild': 'lte_upoctudl', 'feildName': '4G日流量', 'datatype': 'character varying', 'columntype': '1',
     'feildtype': '45G流量与热点评估物理站级', 'table': 'appdbv3.a_cap_ltenr_station', 'tableName': '45G流量与热点评估物理站级'},
    {'feild': 'nr_upoctudl', 'feildName': '5G日流量', 'datatype': 'character varying', 'columntype': '1',
     'feildtype': '45G流量与热点评估物理站级', 'table': 'appdbv3.a_cap_ltenr_station', 'tableName': '45G流量与热点评估物理站级'},
    {'feild': 'total_upoctudl', 'feildName': '45G日总流量', 'datatype': 'character varying', 'columntype': '1',
     'feildtype': '45G流量与热点评估物理站级', 'table': 'appdbv3.a_cap_ltenr_station', 'tableName': '45G流量与热点评估物理站级'},
    {'feild': 'nr_upoctudl_rate', 'feildName': '5G日流量占比', 'datatype': 'character varying', 'columntype': '1',
     'feildtype': '45G流量与热点评估物理站级', 'table': 'appdbv3.a_cap_ltenr_station', 'tableName': '45G流量与热点评估物理站级'},
]
